/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// RoutingProtocolsApiService RoutingProtocolsApi service
type RoutingProtocolsApiService service

type ApiCreateConnectionRoutingProtocolRequest struct {
	ctx                 context.Context
	ApiService          *RoutingProtocolsApiService
	connectionId        string
	routingProtocolBase *RoutingProtocolBase
	xCORRELATIONID      *string
	xAUTHUSERNAME       *string
	xSOURCE             *string
}

func (r ApiCreateConnectionRoutingProtocolRequest) RoutingProtocolBase(routingProtocolBase RoutingProtocolBase) ApiCreateConnectionRoutingProtocolRequest {
	r.routingProtocolBase = &routingProtocolBase
	return r
}

// Correlation identifier
func (r ApiCreateConnectionRoutingProtocolRequest) XCORRELATIONID(xCORRELATIONID string) ApiCreateConnectionRoutingProtocolRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiCreateConnectionRoutingProtocolRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiCreateConnectionRoutingProtocolRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

// source
func (r ApiCreateConnectionRoutingProtocolRequest) XSOURCE(xSOURCE string) ApiCreateConnectionRoutingProtocolRequest {
	r.xSOURCE = &xSOURCE
	return r
}

func (r ApiCreateConnectionRoutingProtocolRequest) Execute() (*RoutingProtocolData, *http.Response, error) {
	return r.ApiService.CreateConnectionRoutingProtocolExecute(r)
}

/*
CreateConnectionRoutingProtocol Create Protocol

This API provides capability to create Routing Protocol for connections

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param connectionId Connection Id
	@return ApiCreateConnectionRoutingProtocolRequest
*/
func (a *RoutingProtocolsApiService) CreateConnectionRoutingProtocol(ctx context.Context, connectionId string) ApiCreateConnectionRoutingProtocolRequest {
	return ApiCreateConnectionRoutingProtocolRequest{
		ApiService:   a,
		ctx:          ctx,
		connectionId: connectionId,
	}
}

// Execute executes the request
//
//	@return RoutingProtocolData
func (a *RoutingProtocolsApiService) CreateConnectionRoutingProtocolExecute(r ApiCreateConnectionRoutingProtocolRequest) (*RoutingProtocolData, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *RoutingProtocolData
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RoutingProtocolsApiService.CreateConnectionRoutingProtocol")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/connections/{connectionId}/routingProtocols"
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "connectionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.routingProtocolBase == nil {
		return localVarReturnValue, nil, reportError("routingProtocolBase is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	if r.xSOURCE != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-SOURCE", r.xSOURCE, "simple", "")
	}
	// body params
	localVarPostBody = r.routingProtocolBase
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 415 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCreateConnectionRoutingProtocolsInBulkRequest struct {
	ctx                                  context.Context
	ApiService                           *RoutingProtocolsApiService
	connectionId                         string
	connectionRoutingProtocolPostRequest *ConnectionRoutingProtocolPostRequest
	xCORRELATIONID                       *string
	xAUTHUSERNAME                        *string
	xSOURCE                              *string
}

func (r ApiCreateConnectionRoutingProtocolsInBulkRequest) ConnectionRoutingProtocolPostRequest(connectionRoutingProtocolPostRequest ConnectionRoutingProtocolPostRequest) ApiCreateConnectionRoutingProtocolsInBulkRequest {
	r.connectionRoutingProtocolPostRequest = &connectionRoutingProtocolPostRequest
	return r
}

// Correlation identifier
func (r ApiCreateConnectionRoutingProtocolsInBulkRequest) XCORRELATIONID(xCORRELATIONID string) ApiCreateConnectionRoutingProtocolsInBulkRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiCreateConnectionRoutingProtocolsInBulkRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiCreateConnectionRoutingProtocolsInBulkRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

// source
func (r ApiCreateConnectionRoutingProtocolsInBulkRequest) XSOURCE(xSOURCE string) ApiCreateConnectionRoutingProtocolsInBulkRequest {
	r.xSOURCE = &xSOURCE
	return r
}

func (r ApiCreateConnectionRoutingProtocolsInBulkRequest) Execute() (*GetResponse, *http.Response, error) {
	return r.ApiService.CreateConnectionRoutingProtocolsInBulkExecute(r)
}

/*
CreateConnectionRoutingProtocolsInBulk Bulk Create Protocol

This API provides capability to create Routing Protocol for connections

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param connectionId Connection Id
	@return ApiCreateConnectionRoutingProtocolsInBulkRequest
*/
func (a *RoutingProtocolsApiService) CreateConnectionRoutingProtocolsInBulk(ctx context.Context, connectionId string) ApiCreateConnectionRoutingProtocolsInBulkRequest {
	return ApiCreateConnectionRoutingProtocolsInBulkRequest{
		ApiService:   a,
		ctx:          ctx,
		connectionId: connectionId,
	}
}

// Execute executes the request
//
//	@return GetResponse
func (a *RoutingProtocolsApiService) CreateConnectionRoutingProtocolsInBulkExecute(r ApiCreateConnectionRoutingProtocolsInBulkRequest) (*GetResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *GetResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RoutingProtocolsApiService.CreateConnectionRoutingProtocolsInBulk")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/connections/{connectionId}/routingProtocols/bulk"
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "connectionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.connectionRoutingProtocolPostRequest == nil {
		return localVarReturnValue, nil, reportError("connectionRoutingProtocolPostRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	if r.xSOURCE != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-SOURCE", r.xSOURCE, "simple", "")
	}
	// body params
	localVarPostBody = r.connectionRoutingProtocolPostRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 415 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteConnectionRoutingProtocolByUuidRequest struct {
	ctx               context.Context
	ApiService        *RoutingProtocolsApiService
	routingProtocolId string
	connectionId      string
	xCORRELATIONID    *string
	xAUTHUSERNAME     *string
	xSOURCE           *string
}

// Correlation identifier
func (r ApiDeleteConnectionRoutingProtocolByUuidRequest) XCORRELATIONID(xCORRELATIONID string) ApiDeleteConnectionRoutingProtocolByUuidRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiDeleteConnectionRoutingProtocolByUuidRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiDeleteConnectionRoutingProtocolByUuidRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

// source
func (r ApiDeleteConnectionRoutingProtocolByUuidRequest) XSOURCE(xSOURCE string) ApiDeleteConnectionRoutingProtocolByUuidRequest {
	r.xSOURCE = &xSOURCE
	return r
}

func (r ApiDeleteConnectionRoutingProtocolByUuidRequest) Execute() (*RoutingProtocolData, *http.Response, error) {
	return r.ApiService.DeleteConnectionRoutingProtocolByUuidExecute(r)
}

/*
DeleteConnectionRoutingProtocolByUuid Delete Protocol

This API provides capability to delete Routing Protocols on virtual connection

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param routingProtocolId Routing Protocol Id
	@param connectionId Connection Id
	@return ApiDeleteConnectionRoutingProtocolByUuidRequest
*/
func (a *RoutingProtocolsApiService) DeleteConnectionRoutingProtocolByUuid(ctx context.Context, routingProtocolId string, connectionId string) ApiDeleteConnectionRoutingProtocolByUuidRequest {
	return ApiDeleteConnectionRoutingProtocolByUuidRequest{
		ApiService:        a,
		ctx:               ctx,
		routingProtocolId: routingProtocolId,
		connectionId:      connectionId,
	}
}

// Execute executes the request
//
//	@return RoutingProtocolData
func (a *RoutingProtocolsApiService) DeleteConnectionRoutingProtocolByUuidExecute(r ApiDeleteConnectionRoutingProtocolByUuidRequest) (*RoutingProtocolData, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodDelete
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *RoutingProtocolData
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RoutingProtocolsApiService.DeleteConnectionRoutingProtocolByUuid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/connections/{connectionId}/routingProtocols/{routingProtocolId}"
	localVarPath = strings.Replace(localVarPath, "{"+"routingProtocolId"+"}", url.PathEscape(parameterValueToString(r.routingProtocolId, "routingProtocolId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "connectionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	if r.xSOURCE != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-SOURCE", r.xSOURCE, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 415 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetConnectionRoutingProtocolAllBgpActionsRequest struct {
	ctx               context.Context
	ApiService        *RoutingProtocolsApiService
	routingProtocolId string
	connectionId      string
	xCORRELATIONID    *string
	xAUTHUSERNAME     *string
	xSOURCE           *string
	offset            *int32
	limit             *int32
}

// Correlation identifier
func (r ApiGetConnectionRoutingProtocolAllBgpActionsRequest) XCORRELATIONID(xCORRELATIONID string) ApiGetConnectionRoutingProtocolAllBgpActionsRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiGetConnectionRoutingProtocolAllBgpActionsRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiGetConnectionRoutingProtocolAllBgpActionsRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

// source
func (r ApiGetConnectionRoutingProtocolAllBgpActionsRequest) XSOURCE(xSOURCE string) ApiGetConnectionRoutingProtocolAllBgpActionsRequest {
	r.xSOURCE = &xSOURCE
	return r
}

// offset
func (r ApiGetConnectionRoutingProtocolAllBgpActionsRequest) Offset(offset int32) ApiGetConnectionRoutingProtocolAllBgpActionsRequest {
	r.offset = &offset
	return r
}

// number of records to fetch
func (r ApiGetConnectionRoutingProtocolAllBgpActionsRequest) Limit(limit int32) ApiGetConnectionRoutingProtocolAllBgpActionsRequest {
	r.limit = &limit
	return r
}

func (r ApiGetConnectionRoutingProtocolAllBgpActionsRequest) Execute() (*BGPActionsBulkData, *http.Response, error) {
	return r.ApiService.GetConnectionRoutingProtocolAllBgpActionsExecute(r)
}

/*
GetConnectionRoutingProtocolAllBgpActions Get BGP Actions

This API provides capability to get all BGP actions status

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param routingProtocolId Routing Protocol Id
	@param connectionId Connection Id
	@return ApiGetConnectionRoutingProtocolAllBgpActionsRequest
*/
func (a *RoutingProtocolsApiService) GetConnectionRoutingProtocolAllBgpActions(ctx context.Context, routingProtocolId string, connectionId string) ApiGetConnectionRoutingProtocolAllBgpActionsRequest {
	return ApiGetConnectionRoutingProtocolAllBgpActionsRequest{
		ApiService:        a,
		ctx:               ctx,
		routingProtocolId: routingProtocolId,
		connectionId:      connectionId,
	}
}

// Execute executes the request
//
//	@return BGPActionsBulkData
func (a *RoutingProtocolsApiService) GetConnectionRoutingProtocolAllBgpActionsExecute(r ApiGetConnectionRoutingProtocolAllBgpActionsRequest) (*BGPActionsBulkData, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *BGPActionsBulkData
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RoutingProtocolsApiService.GetConnectionRoutingProtocolAllBgpActions")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/connections/{connectionId}/routingProtocols/{routingProtocolId}/actions"
	localVarPath = strings.Replace(localVarPath, "{"+"routingProtocolId"+"}", url.PathEscape(parameterValueToString(r.routingProtocolId, "routingProtocolId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "connectionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	if r.xSOURCE != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-SOURCE", r.xSOURCE, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 415 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetConnectionRoutingProtocolByUuidRequest struct {
	ctx               context.Context
	ApiService        *RoutingProtocolsApiService
	routingProtocolId string
	connectionId      string
	xCORRELATIONID    *string
	xAUTHUSERNAME     *string
	xSOURCE           *string
}

// Correlation identifier
func (r ApiGetConnectionRoutingProtocolByUuidRequest) XCORRELATIONID(xCORRELATIONID string) ApiGetConnectionRoutingProtocolByUuidRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiGetConnectionRoutingProtocolByUuidRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiGetConnectionRoutingProtocolByUuidRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

// source
func (r ApiGetConnectionRoutingProtocolByUuidRequest) XSOURCE(xSOURCE string) ApiGetConnectionRoutingProtocolByUuidRequest {
	r.xSOURCE = &xSOURCE
	return r
}

func (r ApiGetConnectionRoutingProtocolByUuidRequest) Execute() (*RoutingProtocolData, *http.Response, error) {
	return r.ApiService.GetConnectionRoutingProtocolByUuidExecute(r)
}

/*
GetConnectionRoutingProtocolByUuid Get Protocol

This API provides capability to accept/reject user's virtual connection

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param routingProtocolId Routing Protocol Id
	@param connectionId Connection Id
	@return ApiGetConnectionRoutingProtocolByUuidRequest
*/
func (a *RoutingProtocolsApiService) GetConnectionRoutingProtocolByUuid(ctx context.Context, routingProtocolId string, connectionId string) ApiGetConnectionRoutingProtocolByUuidRequest {
	return ApiGetConnectionRoutingProtocolByUuidRequest{
		ApiService:        a,
		ctx:               ctx,
		routingProtocolId: routingProtocolId,
		connectionId:      connectionId,
	}
}

// Execute executes the request
//
//	@return RoutingProtocolData
func (a *RoutingProtocolsApiService) GetConnectionRoutingProtocolByUuidExecute(r ApiGetConnectionRoutingProtocolByUuidRequest) (*RoutingProtocolData, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *RoutingProtocolData
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RoutingProtocolsApiService.GetConnectionRoutingProtocolByUuid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/connections/{connectionId}/routingProtocols/{routingProtocolId}"
	localVarPath = strings.Replace(localVarPath, "{"+"routingProtocolId"+"}", url.PathEscape(parameterValueToString(r.routingProtocolId, "routingProtocolId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "connectionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	if r.xSOURCE != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-SOURCE", r.xSOURCE, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 415 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetConnectionRoutingProtocolsRequest struct {
	ctx            context.Context
	ApiService     *RoutingProtocolsApiService
	connectionId   string
	xCORRELATIONID *string
	xAUTHUSERNAME  *string
	xSOURCE        *string
	offset         *int32
	limit          *int32
}

// Correlation identifier
func (r ApiGetConnectionRoutingProtocolsRequest) XCORRELATIONID(xCORRELATIONID string) ApiGetConnectionRoutingProtocolsRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiGetConnectionRoutingProtocolsRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiGetConnectionRoutingProtocolsRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

// source
func (r ApiGetConnectionRoutingProtocolsRequest) XSOURCE(xSOURCE string) ApiGetConnectionRoutingProtocolsRequest {
	r.xSOURCE = &xSOURCE
	return r
}

// offset
func (r ApiGetConnectionRoutingProtocolsRequest) Offset(offset int32) ApiGetConnectionRoutingProtocolsRequest {
	r.offset = &offset
	return r
}

// number of records to fetch
func (r ApiGetConnectionRoutingProtocolsRequest) Limit(limit int32) ApiGetConnectionRoutingProtocolsRequest {
	r.limit = &limit
	return r
}

func (r ApiGetConnectionRoutingProtocolsRequest) Execute() (*GetResponse, *http.Response, error) {
	return r.ApiService.GetConnectionRoutingProtocolsExecute(r)
}

/*
GetConnectionRoutingProtocols GetRoutingProtocols

This API provides capability to get Routing Protocols for connections

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param connectionId Connection Id
	@return ApiGetConnectionRoutingProtocolsRequest
*/
func (a *RoutingProtocolsApiService) GetConnectionRoutingProtocols(ctx context.Context, connectionId string) ApiGetConnectionRoutingProtocolsRequest {
	return ApiGetConnectionRoutingProtocolsRequest{
		ApiService:   a,
		ctx:          ctx,
		connectionId: connectionId,
	}
}

// Execute executes the request
//
//	@return GetResponse
func (a *RoutingProtocolsApiService) GetConnectionRoutingProtocolsExecute(r ApiGetConnectionRoutingProtocolsRequest) (*GetResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *GetResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RoutingProtocolsApiService.GetConnectionRoutingProtocols")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/connections/{connectionId}/routingProtocols"
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "connectionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	if r.xSOURCE != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-SOURCE", r.xSOURCE, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetConnectionRoutingProtocolsBgpActionByUuidRequest struct {
	ctx               context.Context
	ApiService        *RoutingProtocolsApiService
	connectionId      string
	routingProtocolId string
	actionId          string
	xCORRELATIONID    *string
	xAUTHUSERNAME     *string
}

// Correlation identifier
func (r ApiGetConnectionRoutingProtocolsBgpActionByUuidRequest) XCORRELATIONID(xCORRELATIONID string) ApiGetConnectionRoutingProtocolsBgpActionByUuidRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiGetConnectionRoutingProtocolsBgpActionByUuidRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiGetConnectionRoutingProtocolsBgpActionByUuidRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

func (r ApiGetConnectionRoutingProtocolsBgpActionByUuidRequest) Execute() (*BGPActionData, *http.Response, error) {
	return r.ApiService.GetConnectionRoutingProtocolsBgpActionByUuidExecute(r)
}

/*
GetConnectionRoutingProtocolsBgpActionByUuid Get BGP Action

This API provides capability to retrieve specific BGP action

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param connectionId Connection Id
	@param routingProtocolId Routing Protocol Id
	@param actionId BGP Action UUID
	@return ApiGetConnectionRoutingProtocolsBgpActionByUuidRequest
*/
func (a *RoutingProtocolsApiService) GetConnectionRoutingProtocolsBgpActionByUuid(ctx context.Context, connectionId string, routingProtocolId string, actionId string) ApiGetConnectionRoutingProtocolsBgpActionByUuidRequest {
	return ApiGetConnectionRoutingProtocolsBgpActionByUuidRequest{
		ApiService:        a,
		ctx:               ctx,
		connectionId:      connectionId,
		routingProtocolId: routingProtocolId,
		actionId:          actionId,
	}
}

// Execute executes the request
//
//	@return BGPActionData
func (a *RoutingProtocolsApiService) GetConnectionRoutingProtocolsBgpActionByUuidExecute(r ApiGetConnectionRoutingProtocolsBgpActionByUuidRequest) (*BGPActionData, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *BGPActionData
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RoutingProtocolsApiService.GetConnectionRoutingProtocolsBgpActionByUuid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/connections/{connectionId}/routingProtocols/{routingProtocolId}/actions/{actionId}"
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "connectionId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"routingProtocolId"+"}", url.PathEscape(parameterValueToString(r.routingProtocolId, "routingProtocolId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"actionId"+"}", url.PathEscape(parameterValueToString(r.actionId, "actionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetConnectionRoutingProtocolsChangeByUuidRequest struct {
	ctx               context.Context
	ApiService        *RoutingProtocolsApiService
	connectionId      string
	routingProtocolId string
	changeId          string
	xCORRELATIONID    *string
	xAUTHUSERNAME     *string
}

// Correlation identifier
func (r ApiGetConnectionRoutingProtocolsChangeByUuidRequest) XCORRELATIONID(xCORRELATIONID string) ApiGetConnectionRoutingProtocolsChangeByUuidRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiGetConnectionRoutingProtocolsChangeByUuidRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiGetConnectionRoutingProtocolsChangeByUuidRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

func (r ApiGetConnectionRoutingProtocolsChangeByUuidRequest) Execute() (*RoutingProtocolChangeData, *http.Response, error) {
	return r.ApiService.GetConnectionRoutingProtocolsChangeByUuidExecute(r)
}

/*
GetConnectionRoutingProtocolsChangeByUuid Get Change By ID

This API provides capability to retrieve specific Routing Protocol Change

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param connectionId Connection Id
	@param routingProtocolId Routing Protocol Id
	@param changeId Routing Protocol Change UUID
	@return ApiGetConnectionRoutingProtocolsChangeByUuidRequest
*/
func (a *RoutingProtocolsApiService) GetConnectionRoutingProtocolsChangeByUuid(ctx context.Context, connectionId string, routingProtocolId string, changeId string) ApiGetConnectionRoutingProtocolsChangeByUuidRequest {
	return ApiGetConnectionRoutingProtocolsChangeByUuidRequest{
		ApiService:        a,
		ctx:               ctx,
		connectionId:      connectionId,
		routingProtocolId: routingProtocolId,
		changeId:          changeId,
	}
}

// Execute executes the request
//
//	@return RoutingProtocolChangeData
func (a *RoutingProtocolsApiService) GetConnectionRoutingProtocolsChangeByUuidExecute(r ApiGetConnectionRoutingProtocolsChangeByUuidRequest) (*RoutingProtocolChangeData, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *RoutingProtocolChangeData
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RoutingProtocolsApiService.GetConnectionRoutingProtocolsChangeByUuid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/connections/{connectionId}/routingProtocols/{routingProtocolId}/changes/{changeId}"
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "connectionId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"routingProtocolId"+"}", url.PathEscape(parameterValueToString(r.routingProtocolId, "routingProtocolId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"changeId"+"}", url.PathEscape(parameterValueToString(r.changeId, "changeId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetConnectionRoutingProtocolsChangesRequest struct {
	ctx               context.Context
	ApiService        *RoutingProtocolsApiService
	connectionId      string
	routingProtocolId string
	xCORRELATIONID    *string
	xAUTHUSERNAME     *string
	offset            *int32
	limit             *int32
}

// Correlation identifier
func (r ApiGetConnectionRoutingProtocolsChangesRequest) XCORRELATIONID(xCORRELATIONID string) ApiGetConnectionRoutingProtocolsChangesRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiGetConnectionRoutingProtocolsChangesRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiGetConnectionRoutingProtocolsChangesRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

// offset
func (r ApiGetConnectionRoutingProtocolsChangesRequest) Offset(offset int32) ApiGetConnectionRoutingProtocolsChangesRequest {
	r.offset = &offset
	return r
}

// number of records to fetch
func (r ApiGetConnectionRoutingProtocolsChangesRequest) Limit(limit int32) ApiGetConnectionRoutingProtocolsChangesRequest {
	r.limit = &limit
	return r
}

func (r ApiGetConnectionRoutingProtocolsChangesRequest) Execute() (*RoutingProtocolChangeDataResponse, *http.Response, error) {
	return r.ApiService.GetConnectionRoutingProtocolsChangesExecute(r)
}

/*
GetConnectionRoutingProtocolsChanges Get Changes

This API provides capability to retrieve user's Routing Protocol Changes

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param connectionId Connection Id
	@param routingProtocolId Routing Protocol Id
	@return ApiGetConnectionRoutingProtocolsChangesRequest
*/
func (a *RoutingProtocolsApiService) GetConnectionRoutingProtocolsChanges(ctx context.Context, connectionId string, routingProtocolId string) ApiGetConnectionRoutingProtocolsChangesRequest {
	return ApiGetConnectionRoutingProtocolsChangesRequest{
		ApiService:        a,
		ctx:               ctx,
		connectionId:      connectionId,
		routingProtocolId: routingProtocolId,
	}
}

// Execute executes the request
//
//	@return RoutingProtocolChangeDataResponse
func (a *RoutingProtocolsApiService) GetConnectionRoutingProtocolsChangesExecute(r ApiGetConnectionRoutingProtocolsChangesRequest) (*RoutingProtocolChangeDataResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *RoutingProtocolChangeDataResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RoutingProtocolsApiService.GetConnectionRoutingProtocolsChanges")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/connections/{connectionId}/routingProtocols/{routingProtocolId}/changes"
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "connectionId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"routingProtocolId"+"}", url.PathEscape(parameterValueToString(r.routingProtocolId, "routingProtocolId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPatchConnectionRoutingProtocolByUuidRequest struct {
	ctx                       context.Context
	ApiService                *RoutingProtocolsApiService
	routingProtocolId         string
	connectionId              string
	connectionChangeOperation *[]ConnectionChangeOperation
	xCORRELATIONID            *string
	xAUTHUSERNAME             *string
	xSOURCE                   *string
}

func (r ApiPatchConnectionRoutingProtocolByUuidRequest) ConnectionChangeOperation(connectionChangeOperation []ConnectionChangeOperation) ApiPatchConnectionRoutingProtocolByUuidRequest {
	r.connectionChangeOperation = &connectionChangeOperation
	return r
}

// Correlation identifier
func (r ApiPatchConnectionRoutingProtocolByUuidRequest) XCORRELATIONID(xCORRELATIONID string) ApiPatchConnectionRoutingProtocolByUuidRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiPatchConnectionRoutingProtocolByUuidRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiPatchConnectionRoutingProtocolByUuidRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

// source
func (r ApiPatchConnectionRoutingProtocolByUuidRequest) XSOURCE(xSOURCE string) ApiPatchConnectionRoutingProtocolByUuidRequest {
	r.xSOURCE = &xSOURCE
	return r
}

func (r ApiPatchConnectionRoutingProtocolByUuidRequest) Execute() (*RoutingProtocolData, *http.Response, error) {
	return r.ApiService.PatchConnectionRoutingProtocolByUuidExecute(r)
}

/*
PatchConnectionRoutingProtocolByUuid Patch Protocol

This API provides capability to partially update Routing Protocols on a virtual connection

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param routingProtocolId Routing Protocol Id
	@param connectionId Connection Id
	@return ApiPatchConnectionRoutingProtocolByUuidRequest
*/
func (a *RoutingProtocolsApiService) PatchConnectionRoutingProtocolByUuid(ctx context.Context, routingProtocolId string, connectionId string) ApiPatchConnectionRoutingProtocolByUuidRequest {
	return ApiPatchConnectionRoutingProtocolByUuidRequest{
		ApiService:        a,
		ctx:               ctx,
		routingProtocolId: routingProtocolId,
		connectionId:      connectionId,
	}
}

// Execute executes the request
//
//	@return RoutingProtocolData
func (a *RoutingProtocolsApiService) PatchConnectionRoutingProtocolByUuidExecute(r ApiPatchConnectionRoutingProtocolByUuidRequest) (*RoutingProtocolData, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *RoutingProtocolData
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RoutingProtocolsApiService.PatchConnectionRoutingProtocolByUuid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/connections/{connectionId}/routingProtocols/{routingProtocolId}"
	localVarPath = strings.Replace(localVarPath, "{"+"routingProtocolId"+"}", url.PathEscape(parameterValueToString(r.routingProtocolId, "routingProtocolId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "connectionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.connectionChangeOperation == nil {
		return localVarReturnValue, nil, reportError("connectionChangeOperation is required and must be specified")
	}
	if len(*r.connectionChangeOperation) < 1 {
		return localVarReturnValue, nil, reportError("connectionChangeOperation must have at least 1 elements")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	if r.xSOURCE != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-SOURCE", r.xSOURCE, "simple", "")
	}
	// body params
	localVarPostBody = r.connectionChangeOperation
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 415 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPostConnectionRoutingProtocolBgpActionByUuidRequest struct {
	ctx               context.Context
	ApiService        *RoutingProtocolsApiService
	routingProtocolId string
	connectionId      string
	bGPActionRequest  *BGPActionRequest
	xCORRELATIONID    *string
	xAUTHUSERNAME     *string
	xSOURCE           *string
}

func (r ApiPostConnectionRoutingProtocolBgpActionByUuidRequest) BGPActionRequest(bGPActionRequest BGPActionRequest) ApiPostConnectionRoutingProtocolBgpActionByUuidRequest {
	r.bGPActionRequest = &bGPActionRequest
	return r
}

// Correlation identifier
func (r ApiPostConnectionRoutingProtocolBgpActionByUuidRequest) XCORRELATIONID(xCORRELATIONID string) ApiPostConnectionRoutingProtocolBgpActionByUuidRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiPostConnectionRoutingProtocolBgpActionByUuidRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiPostConnectionRoutingProtocolBgpActionByUuidRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

// source
func (r ApiPostConnectionRoutingProtocolBgpActionByUuidRequest) XSOURCE(xSOURCE string) ApiPostConnectionRoutingProtocolBgpActionByUuidRequest {
	r.xSOURCE = &xSOURCE
	return r
}

func (r ApiPostConnectionRoutingProtocolBgpActionByUuidRequest) Execute() (*BGPActionData, *http.Response, error) {
	return r.ApiService.PostConnectionRoutingProtocolBgpActionByUuidExecute(r)
}

/*
PostConnectionRoutingProtocolBgpActionByUuid Clear/Reset BGP

This API provides capability to clear/reset Routing Protocols BGP session

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param routingProtocolId Routing Protocol Id
	@param connectionId Connection Id
	@return ApiPostConnectionRoutingProtocolBgpActionByUuidRequest
*/
func (a *RoutingProtocolsApiService) PostConnectionRoutingProtocolBgpActionByUuid(ctx context.Context, routingProtocolId string, connectionId string) ApiPostConnectionRoutingProtocolBgpActionByUuidRequest {
	return ApiPostConnectionRoutingProtocolBgpActionByUuidRequest{
		ApiService:        a,
		ctx:               ctx,
		routingProtocolId: routingProtocolId,
		connectionId:      connectionId,
	}
}

// Execute executes the request
//
//	@return BGPActionData
func (a *RoutingProtocolsApiService) PostConnectionRoutingProtocolBgpActionByUuidExecute(r ApiPostConnectionRoutingProtocolBgpActionByUuidRequest) (*BGPActionData, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *BGPActionData
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RoutingProtocolsApiService.PostConnectionRoutingProtocolBgpActionByUuid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/connections/{connectionId}/routingProtocols/{routingProtocolId}/actions"
	localVarPath = strings.Replace(localVarPath, "{"+"routingProtocolId"+"}", url.PathEscape(parameterValueToString(r.routingProtocolId, "routingProtocolId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "connectionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.bGPActionRequest == nil {
		return localVarReturnValue, nil, reportError("bGPActionRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	if r.xSOURCE != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-SOURCE", r.xSOURCE, "simple", "")
	}
	// body params
	localVarPostBody = r.bGPActionRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 415 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiReplaceConnectionRoutingProtocolByUuidRequest struct {
	ctx                 context.Context
	ApiService          *RoutingProtocolsApiService
	routingProtocolId   string
	connectionId        string
	routingProtocolBase *RoutingProtocolBase
	xCORRELATIONID      *string
	xAUTHUSERNAME       *string
	xSOURCE             *string
}

func (r ApiReplaceConnectionRoutingProtocolByUuidRequest) RoutingProtocolBase(routingProtocolBase RoutingProtocolBase) ApiReplaceConnectionRoutingProtocolByUuidRequest {
	r.routingProtocolBase = &routingProtocolBase
	return r
}

// Correlation identifier
func (r ApiReplaceConnectionRoutingProtocolByUuidRequest) XCORRELATIONID(xCORRELATIONID string) ApiReplaceConnectionRoutingProtocolByUuidRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiReplaceConnectionRoutingProtocolByUuidRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiReplaceConnectionRoutingProtocolByUuidRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

// source
func (r ApiReplaceConnectionRoutingProtocolByUuidRequest) XSOURCE(xSOURCE string) ApiReplaceConnectionRoutingProtocolByUuidRequest {
	r.xSOURCE = &xSOURCE
	return r
}

func (r ApiReplaceConnectionRoutingProtocolByUuidRequest) Execute() (*RoutingProtocolData, *http.Response, error) {
	return r.ApiService.ReplaceConnectionRoutingProtocolByUuidExecute(r)
}

/*
ReplaceConnectionRoutingProtocolByUuid Replace Protocol

This API provides capability to replace complete Routing Protocols on a virtual connection

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param routingProtocolId Routing Protocol Id
	@param connectionId Connection Id
	@return ApiReplaceConnectionRoutingProtocolByUuidRequest
*/
func (a *RoutingProtocolsApiService) ReplaceConnectionRoutingProtocolByUuid(ctx context.Context, routingProtocolId string, connectionId string) ApiReplaceConnectionRoutingProtocolByUuidRequest {
	return ApiReplaceConnectionRoutingProtocolByUuidRequest{
		ApiService:        a,
		ctx:               ctx,
		routingProtocolId: routingProtocolId,
		connectionId:      connectionId,
	}
}

// Execute executes the request
//
//	@return RoutingProtocolData
func (a *RoutingProtocolsApiService) ReplaceConnectionRoutingProtocolByUuidExecute(r ApiReplaceConnectionRoutingProtocolByUuidRequest) (*RoutingProtocolData, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *RoutingProtocolData
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RoutingProtocolsApiService.ReplaceConnectionRoutingProtocolByUuid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/connections/{connectionId}/routingProtocols/{routingProtocolId}"
	localVarPath = strings.Replace(localVarPath, "{"+"routingProtocolId"+"}", url.PathEscape(parameterValueToString(r.routingProtocolId, "routingProtocolId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"connectionId"+"}", url.PathEscape(parameterValueToString(r.connectionId, "connectionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.routingProtocolBase == nil {
		return localVarReturnValue, nil, reportError("routingProtocolBase is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	if r.xSOURCE != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-SOURCE", r.xSOURCE, "simple", "")
	}
	// body params
	localVarPostBody = r.routingProtocolBase
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 415 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiValidateRoutingProtocolRequest struct {
	ctx             context.Context
	ApiService      *RoutingProtocolsApiService
	routerId        string
	validateRequest *ValidateRequest
	xCORRELATIONID  *string
	xAUTHUSERNAME   *string
}

func (r ApiValidateRoutingProtocolRequest) ValidateRequest(validateRequest ValidateRequest) ApiValidateRoutingProtocolRequest {
	r.validateRequest = &validateRequest
	return r
}

// Correlation identifier
func (r ApiValidateRoutingProtocolRequest) XCORRELATIONID(xCORRELATIONID string) ApiValidateRoutingProtocolRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiValidateRoutingProtocolRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiValidateRoutingProtocolRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

func (r ApiValidateRoutingProtocolRequest) Execute() (*ValidateSubnetResponse, *http.Response, error) {
	return r.ApiService.ValidateRoutingProtocolExecute(r)
}

/*
ValidateRoutingProtocol Validate Subnet

This API provides capability to validate all subnets associated with any connection in the given FCR

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param routerId Cloud Router UUID
	@return ApiValidateRoutingProtocolRequest
*/
func (a *RoutingProtocolsApiService) ValidateRoutingProtocol(ctx context.Context, routerId string) ApiValidateRoutingProtocolRequest {
	return ApiValidateRoutingProtocolRequest{
		ApiService: a,
		ctx:        ctx,
		routerId:   routerId,
	}
}

// Execute executes the request
//
//	@return ValidateSubnetResponse
func (a *RoutingProtocolsApiService) ValidateRoutingProtocolExecute(r ApiValidateRoutingProtocolRequest) (*ValidateSubnetResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ValidateSubnetResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RoutingProtocolsApiService.ValidateRoutingProtocol")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/routers/{routerId}/validate"
	localVarPath = strings.Replace(localVarPath, "{"+"routerId"+"}", url.PathEscape(parameterValueToString(r.routerId, "routerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.validateRequest == nil {
		return localVarReturnValue, nil, reportError("validateRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	// body params
	localVarPostBody = r.validateRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
