/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// ServiceProfilesApiService ServiceProfilesApi service
type ServiceProfilesApiService service

type ApiCreateServiceProfileRequest struct {
	ctx                   context.Context
	ApiService            *ServiceProfilesApiService
	icVersion             *string
	serviceProfileRequest *ServiceProfileRequest
	xCORRELATIONID        *string
	xAUTHUSERNAME         *string
}

// api version
func (r ApiCreateServiceProfileRequest) IcVersion(icVersion string) ApiCreateServiceProfileRequest {
	r.icVersion = &icVersion
	return r
}

func (r ApiCreateServiceProfileRequest) ServiceProfileRequest(serviceProfileRequest ServiceProfileRequest) ApiCreateServiceProfileRequest {
	r.serviceProfileRequest = &serviceProfileRequest
	return r
}

// Correlation identifier
func (r ApiCreateServiceProfileRequest) XCORRELATIONID(xCORRELATIONID string) ApiCreateServiceProfileRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiCreateServiceProfileRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiCreateServiceProfileRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

func (r ApiCreateServiceProfileRequest) Execute() (*ServiceProfile, *http.Response, error) {
	return r.ApiService.CreateServiceProfileExecute(r)
}

/*
CreateServiceProfile Create Profile

Create Service Profile creates Equinix Fabric™ Service Profile.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCreateServiceProfileRequest
*/
func (a *ServiceProfilesApiService) CreateServiceProfile(ctx context.Context) ApiCreateServiceProfileRequest {
	return ApiCreateServiceProfileRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ServiceProfile
func (a *ServiceProfilesApiService) CreateServiceProfileExecute(r ApiCreateServiceProfileRequest) (*ServiceProfile, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ServiceProfile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ServiceProfilesApiService.CreateServiceProfile")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/serviceProfiles"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.icVersion == nil {
		return localVarReturnValue, nil, reportError("icVersion is required and must be specified")
	}
	if r.serviceProfileRequest == nil {
		return localVarReturnValue, nil, reportError("serviceProfileRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json; charset=UTF-8", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Ic-Version", r.icVersion, "simple", "")
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	// body params
	localVarPostBody = r.serviceProfileRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteServiceProfileByUuidRequest struct {
	ctx              context.Context
	ApiService       *ServiceProfilesApiService
	serviceProfileId string
	icVersion        *string
	xCORRELATIONID   *string
	xAUTHUSERNAME    *string
}

// api version
func (r ApiDeleteServiceProfileByUuidRequest) IcVersion(icVersion string) ApiDeleteServiceProfileByUuidRequest {
	r.icVersion = &icVersion
	return r
}

// Correlation identifier
func (r ApiDeleteServiceProfileByUuidRequest) XCORRELATIONID(xCORRELATIONID string) ApiDeleteServiceProfileByUuidRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiDeleteServiceProfileByUuidRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiDeleteServiceProfileByUuidRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

func (r ApiDeleteServiceProfileByUuidRequest) Execute() (*ServiceProfile, *http.Response, error) {
	return r.ApiService.DeleteServiceProfileByUuidExecute(r)
}

/*
DeleteServiceProfileByUuid Delete Profile

delete Service Profile by UUID

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param serviceProfileId Service Profile UUID
	@return ApiDeleteServiceProfileByUuidRequest
*/
func (a *ServiceProfilesApiService) DeleteServiceProfileByUuid(ctx context.Context, serviceProfileId string) ApiDeleteServiceProfileByUuidRequest {
	return ApiDeleteServiceProfileByUuidRequest{
		ApiService:       a,
		ctx:              ctx,
		serviceProfileId: serviceProfileId,
	}
}

// Execute executes the request
//
//	@return ServiceProfile
func (a *ServiceProfilesApiService) DeleteServiceProfileByUuidExecute(r ApiDeleteServiceProfileByUuidRequest) (*ServiceProfile, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodDelete
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ServiceProfile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ServiceProfilesApiService.DeleteServiceProfileByUuid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/serviceProfiles/{serviceProfileId}"
	localVarPath = strings.Replace(localVarPath, "{"+"serviceProfileId"+"}", url.PathEscape(parameterValueToString(r.serviceProfileId, "serviceProfileId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.icVersion == nil {
		return localVarReturnValue, nil, reportError("icVersion is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json; charset=UTF-8", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Ic-Version", r.icVersion, "simple", "")
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetServiceProfileByUuidRequest struct {
	ctx              context.Context
	ApiService       *ServiceProfilesApiService
	serviceProfileId string
	icVersion        *string
	xCORRELATIONID   *string
	viewPoint        *GetServiceProfilesViewPointParameter
	style            *GetServiceProfilesStyleParameter
	xAUTHUSERNAME    *string
}

// api version
func (r ApiGetServiceProfileByUuidRequest) IcVersion(icVersion string) ApiGetServiceProfileByUuidRequest {
	r.icVersion = &icVersion
	return r
}

// Correlation identifier
func (r ApiGetServiceProfileByUuidRequest) XCORRELATIONID(xCORRELATIONID string) ApiGetServiceProfileByUuidRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// flips view between buyer and seller representation
func (r ApiGetServiceProfileByUuidRequest) ViewPoint(viewPoint GetServiceProfilesViewPointParameter) ApiGetServiceProfileByUuidRequest {
	r.viewPoint = &viewPoint
	return r
}

// style
func (r ApiGetServiceProfileByUuidRequest) Style(style GetServiceProfilesStyleParameter) ApiGetServiceProfileByUuidRequest {
	r.style = &style
	return r
}

// User name
func (r ApiGetServiceProfileByUuidRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiGetServiceProfileByUuidRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

func (r ApiGetServiceProfileByUuidRequest) Execute() (*ServiceProfile, *http.Response, error) {
	return r.ApiService.GetServiceProfileByUuidExecute(r)
}

/*
GetServiceProfileByUuid Get Profile

Get service profile by UUID. View Point parameter if set to zSide will give seller's view of the profile otherwise buyer's view.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param serviceProfileId Service Profile UUID
	@return ApiGetServiceProfileByUuidRequest
*/
func (a *ServiceProfilesApiService) GetServiceProfileByUuid(ctx context.Context, serviceProfileId string) ApiGetServiceProfileByUuidRequest {
	return ApiGetServiceProfileByUuidRequest{
		ApiService:       a,
		ctx:              ctx,
		serviceProfileId: serviceProfileId,
	}
}

// Execute executes the request
//
//	@return ServiceProfile
func (a *ServiceProfilesApiService) GetServiceProfileByUuidExecute(r ApiGetServiceProfileByUuidRequest) (*ServiceProfile, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ServiceProfile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ServiceProfilesApiService.GetServiceProfileByUuid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/serviceProfiles/{serviceProfileId}"
	localVarPath = strings.Replace(localVarPath, "{"+"serviceProfileId"+"}", url.PathEscape(parameterValueToString(r.serviceProfileId, "serviceProfileId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.icVersion == nil {
		return localVarReturnValue, nil, reportError("icVersion is required and must be specified")
	}

	if r.viewPoint != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "viewPoint", r.viewPoint, "form", "")
	} else {
		var defaultValue GetServiceProfilesViewPointParameter = "aSide"
		r.viewPoint = &defaultValue
	}
	if r.style != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "style", r.style, "form", "")
	} else {
		var defaultValue GetServiceProfilesStyleParameter = "MAX"
		r.style = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json; charset=UTF-8", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Ic-Version", r.icVersion, "simple", "")
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetServiceProfileMetrosByUuidRequest struct {
	ctx              context.Context
	ApiService       *ServiceProfilesApiService
	serviceProfileId string
	icVersion        *string
	xCORRELATIONID   *string
	offset           *int32
	limit            *int32
	style            *GetServiceProfilesStyleParameter
	xAUTHUSERNAME    *string
}

// api version
func (r ApiGetServiceProfileMetrosByUuidRequest) IcVersion(icVersion string) ApiGetServiceProfileMetrosByUuidRequest {
	r.icVersion = &icVersion
	return r
}

// Correlation identifier
func (r ApiGetServiceProfileMetrosByUuidRequest) XCORRELATIONID(xCORRELATIONID string) ApiGetServiceProfileMetrosByUuidRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// offset
func (r ApiGetServiceProfileMetrosByUuidRequest) Offset(offset int32) ApiGetServiceProfileMetrosByUuidRequest {
	r.offset = &offset
	return r
}

// number of records to fetch
func (r ApiGetServiceProfileMetrosByUuidRequest) Limit(limit int32) ApiGetServiceProfileMetrosByUuidRequest {
	r.limit = &limit
	return r
}

// style
func (r ApiGetServiceProfileMetrosByUuidRequest) Style(style GetServiceProfilesStyleParameter) ApiGetServiceProfileMetrosByUuidRequest {
	r.style = &style
	return r
}

// User name
func (r ApiGetServiceProfileMetrosByUuidRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiGetServiceProfileMetrosByUuidRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

func (r ApiGetServiceProfileMetrosByUuidRequest) Execute() (*ServiceMetros, *http.Response, error) {
	return r.ApiService.GetServiceProfileMetrosByUuidExecute(r)
}

/*
GetServiceProfileMetrosByUuid Get Profile Metros

Get service profile metros by UUID.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param serviceProfileId Service Profile UUID
	@return ApiGetServiceProfileMetrosByUuidRequest
*/
func (a *ServiceProfilesApiService) GetServiceProfileMetrosByUuid(ctx context.Context, serviceProfileId string) ApiGetServiceProfileMetrosByUuidRequest {
	return ApiGetServiceProfileMetrosByUuidRequest{
		ApiService:       a,
		ctx:              ctx,
		serviceProfileId: serviceProfileId,
	}
}

// Execute executes the request
//
//	@return ServiceMetros
func (a *ServiceProfilesApiService) GetServiceProfileMetrosByUuidExecute(r ApiGetServiceProfileMetrosByUuidRequest) (*ServiceMetros, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ServiceMetros
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ServiceProfilesApiService.GetServiceProfileMetrosByUuid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/serviceProfiles/{serviceProfileId}/metros"
	localVarPath = strings.Replace(localVarPath, "{"+"serviceProfileId"+"}", url.PathEscape(parameterValueToString(r.serviceProfileId, "serviceProfileId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.icVersion == nil {
		return localVarReturnValue, nil, reportError("icVersion is required and must be specified")
	}

	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.style != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "style", r.style, "form", "")
	} else {
		var defaultValue GetServiceProfilesStyleParameter = "MAX"
		r.style = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json; charset=UTF-8", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Ic-Version", r.icVersion, "simple", "")
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetServiceProfilesRequest struct {
	ctx            context.Context
	ApiService     *ServiceProfilesApiService
	icVersion      *string
	xCORRELATIONID *string
	offset         *int32
	limit          *int32
	viewPoint      *GetServiceProfilesViewPointParameter
	style          *GetServiceProfilesStyleParameter
	xAUTHUSERNAME  *string
}

// api version
func (r ApiGetServiceProfilesRequest) IcVersion(icVersion string) ApiGetServiceProfilesRequest {
	r.icVersion = &icVersion
	return r
}

// Correlation identifier
func (r ApiGetServiceProfilesRequest) XCORRELATIONID(xCORRELATIONID string) ApiGetServiceProfilesRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// offset
func (r ApiGetServiceProfilesRequest) Offset(offset int32) ApiGetServiceProfilesRequest {
	r.offset = &offset
	return r
}

// number of records to fetch
func (r ApiGetServiceProfilesRequest) Limit(limit int32) ApiGetServiceProfilesRequest {
	r.limit = &limit
	return r
}

// flips view between buyer and seller representation
func (r ApiGetServiceProfilesRequest) ViewPoint(viewPoint GetServiceProfilesViewPointParameter) ApiGetServiceProfilesRequest {
	r.viewPoint = &viewPoint
	return r
}

// style
func (r ApiGetServiceProfilesRequest) Style(style GetServiceProfilesStyleParameter) ApiGetServiceProfilesRequest {
	r.style = &style
	return r
}

// User name
func (r ApiGetServiceProfilesRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiGetServiceProfilesRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

func (r ApiGetServiceProfilesRequest) Execute() (*ServiceProfiles, *http.Response, error) {
	return r.ApiService.GetServiceProfilesExecute(r)
}

/*
GetServiceProfiles Get all Profiles

The API request returns all Equinix Fabric Service Profiles in accordance with the view point requested.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetServiceProfilesRequest
*/
func (a *ServiceProfilesApiService) GetServiceProfiles(ctx context.Context) ApiGetServiceProfilesRequest {
	return ApiGetServiceProfilesRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ServiceProfiles
func (a *ServiceProfilesApiService) GetServiceProfilesExecute(r ApiGetServiceProfilesRequest) (*ServiceProfiles, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ServiceProfiles
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ServiceProfilesApiService.GetServiceProfiles")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/serviceProfiles"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.icVersion == nil {
		return localVarReturnValue, nil, reportError("icVersion is required and must be specified")
	}

	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.viewPoint != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "viewPoint", r.viewPoint, "form", "")
	} else {
		var defaultValue GetServiceProfilesViewPointParameter = "aSide"
		r.viewPoint = &defaultValue
	}
	if r.style != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "style", r.style, "form", "")
	} else {
		var defaultValue GetServiceProfilesStyleParameter = "MAX"
		r.style = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json; charset=UTF-8", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Ic-Version", r.icVersion, "simple", "")
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPutServiceProfileByUuidRequest struct {
	ctx                   context.Context
	ApiService            *ServiceProfilesApiService
	serviceProfileId      string
	ifMatch               *string
	icVersion             *string
	serviceProfileRequest *ServiceProfileRequest
	xCORRELATIONID        *string
	xAUTHUSERNAME         *string
}

// conditional request
func (r ApiPutServiceProfileByUuidRequest) IfMatch(ifMatch string) ApiPutServiceProfileByUuidRequest {
	r.ifMatch = &ifMatch
	return r
}

// api version
func (r ApiPutServiceProfileByUuidRequest) IcVersion(icVersion string) ApiPutServiceProfileByUuidRequest {
	r.icVersion = &icVersion
	return r
}

func (r ApiPutServiceProfileByUuidRequest) ServiceProfileRequest(serviceProfileRequest ServiceProfileRequest) ApiPutServiceProfileByUuidRequest {
	r.serviceProfileRequest = &serviceProfileRequest
	return r
}

// Correlation identifier
func (r ApiPutServiceProfileByUuidRequest) XCORRELATIONID(xCORRELATIONID string) ApiPutServiceProfileByUuidRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiPutServiceProfileByUuidRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiPutServiceProfileByUuidRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

func (r ApiPutServiceProfileByUuidRequest) Execute() (*ServiceProfile, *http.Response, error) {
	return r.ApiService.PutServiceProfileByUuidExecute(r)
}

/*
PutServiceProfileByUuid Replace Profile

This API request replaces a service profile definition

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param serviceProfileId Service Profile UUID
	@return ApiPutServiceProfileByUuidRequest
*/
func (a *ServiceProfilesApiService) PutServiceProfileByUuid(ctx context.Context, serviceProfileId string) ApiPutServiceProfileByUuidRequest {
	return ApiPutServiceProfileByUuidRequest{
		ApiService:       a,
		ctx:              ctx,
		serviceProfileId: serviceProfileId,
	}
}

// Execute executes the request
//
//	@return ServiceProfile
func (a *ServiceProfilesApiService) PutServiceProfileByUuidExecute(r ApiPutServiceProfileByUuidRequest) (*ServiceProfile, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ServiceProfile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ServiceProfilesApiService.PutServiceProfileByUuid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/serviceProfiles/{serviceProfileId}"
	localVarPath = strings.Replace(localVarPath, "{"+"serviceProfileId"+"}", url.PathEscape(parameterValueToString(r.serviceProfileId, "serviceProfileId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.ifMatch == nil {
		return localVarReturnValue, nil, reportError("ifMatch is required and must be specified")
	}
	if r.icVersion == nil {
		return localVarReturnValue, nil, reportError("icVersion is required and must be specified")
	}
	if r.serviceProfileRequest == nil {
		return localVarReturnValue, nil, reportError("serviceProfileRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json; charset=UTF-8", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "If-Match", r.ifMatch, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Ic-Version", r.icVersion, "simple", "")
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	// body params
	localVarPostBody = r.serviceProfileRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiSearchServiceProfilesRequest struct {
	ctx                         context.Context
	ApiService                  *ServiceProfilesApiService
	icVersion                   *string
	serviceProfileSearchRequest *ServiceProfileSearchRequest
	xCORRELATIONID              *string
	xAUTHUSERNAME               *string
	viewPoint                   *GetServiceProfilesViewPointParameter
}

// api version
func (r ApiSearchServiceProfilesRequest) IcVersion(icVersion string) ApiSearchServiceProfilesRequest {
	r.icVersion = &icVersion
	return r
}

func (r ApiSearchServiceProfilesRequest) ServiceProfileSearchRequest(serviceProfileSearchRequest ServiceProfileSearchRequest) ApiSearchServiceProfilesRequest {
	r.serviceProfileSearchRequest = &serviceProfileSearchRequest
	return r
}

// Correlation identifier
func (r ApiSearchServiceProfilesRequest) XCORRELATIONID(xCORRELATIONID string) ApiSearchServiceProfilesRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiSearchServiceProfilesRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiSearchServiceProfilesRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

// flips view between buyer and seller representation
func (r ApiSearchServiceProfilesRequest) ViewPoint(viewPoint GetServiceProfilesViewPointParameter) ApiSearchServiceProfilesRequest {
	r.viewPoint = &viewPoint
	return r
}

func (r ApiSearchServiceProfilesRequest) Execute() (*ServiceProfiles, *http.Response, error) {
	return r.ApiService.SearchServiceProfilesExecute(r)
}

/*
SearchServiceProfiles Profile Search

Search service profiles by search criteria

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiSearchServiceProfilesRequest
*/
func (a *ServiceProfilesApiService) SearchServiceProfiles(ctx context.Context) ApiSearchServiceProfilesRequest {
	return ApiSearchServiceProfilesRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ServiceProfiles
func (a *ServiceProfilesApiService) SearchServiceProfilesExecute(r ApiSearchServiceProfilesRequest) (*ServiceProfiles, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ServiceProfiles
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ServiceProfilesApiService.SearchServiceProfiles")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/serviceProfiles/search"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.icVersion == nil {
		return localVarReturnValue, nil, reportError("icVersion is required and must be specified")
	}
	if r.serviceProfileSearchRequest == nil {
		return localVarReturnValue, nil, reportError("serviceProfileSearchRequest is required and must be specified")
	}

	if r.viewPoint != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "viewPoint", r.viewPoint, "form", "")
	} else {
		var defaultValue GetServiceProfilesViewPointParameter = "aSide"
		r.viewPoint = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json; charset=UTF-8", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Ic-Version", r.icVersion, "simple", "")
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	// body params
	localVarPostBody = r.serviceProfileSearchRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateServiceProfileByUuidRequest struct {
	ctx                context.Context
	ApiService         *ServiceProfilesApiService
	serviceProfileId   string
	ifMatch            *string
	icVersion          *string
	jsonPatchOperation *[]JsonPatchOperation
	xCORRELATIONID     *string
	xAUTHUSERNAME      *string
}

// conditional request
func (r ApiUpdateServiceProfileByUuidRequest) IfMatch(ifMatch string) ApiUpdateServiceProfileByUuidRequest {
	r.ifMatch = &ifMatch
	return r
}

// api version
func (r ApiUpdateServiceProfileByUuidRequest) IcVersion(icVersion string) ApiUpdateServiceProfileByUuidRequest {
	r.icVersion = &icVersion
	return r
}

func (r ApiUpdateServiceProfileByUuidRequest) JsonPatchOperation(jsonPatchOperation []JsonPatchOperation) ApiUpdateServiceProfileByUuidRequest {
	r.jsonPatchOperation = &jsonPatchOperation
	return r
}

// Correlation identifier
func (r ApiUpdateServiceProfileByUuidRequest) XCORRELATIONID(xCORRELATIONID string) ApiUpdateServiceProfileByUuidRequest {
	r.xCORRELATIONID = &xCORRELATIONID
	return r
}

// User name
func (r ApiUpdateServiceProfileByUuidRequest) XAUTHUSERNAME(xAUTHUSERNAME string) ApiUpdateServiceProfileByUuidRequest {
	r.xAUTHUSERNAME = &xAUTHUSERNAME
	return r
}

func (r ApiUpdateServiceProfileByUuidRequest) Execute() (*ServiceProfile, *http.Response, error) {
	return r.ApiService.UpdateServiceProfileByUuidExecute(r)
}

/*
UpdateServiceProfileByUuid Update Profile

Update Service Profile by UUID

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param serviceProfileId Service Profile UUID
	@return ApiUpdateServiceProfileByUuidRequest
*/
func (a *ServiceProfilesApiService) UpdateServiceProfileByUuid(ctx context.Context, serviceProfileId string) ApiUpdateServiceProfileByUuidRequest {
	return ApiUpdateServiceProfileByUuidRequest{
		ApiService:       a,
		ctx:              ctx,
		serviceProfileId: serviceProfileId,
	}
}

// Execute executes the request
//
//	@return ServiceProfile
func (a *ServiceProfilesApiService) UpdateServiceProfileByUuidExecute(r ApiUpdateServiceProfileByUuidRequest) (*ServiceProfile, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ServiceProfile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ServiceProfilesApiService.UpdateServiceProfileByUuid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fabric/v4/serviceProfiles/{serviceProfileId}"
	localVarPath = strings.Replace(localVarPath, "{"+"serviceProfileId"+"}", url.PathEscape(parameterValueToString(r.serviceProfileId, "serviceProfileId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.ifMatch == nil {
		return localVarReturnValue, nil, reportError("ifMatch is required and must be specified")
	}
	if r.icVersion == nil {
		return localVarReturnValue, nil, reportError("icVersion is required and must be specified")
	}
	if r.jsonPatchOperation == nil {
		return localVarReturnValue, nil, reportError("jsonPatchOperation is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json-patch+json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json; charset=UTF-8", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "If-Match", r.ifMatch, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Ic-Version", r.icVersion, "simple", "")
	if r.xCORRELATIONID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-CORRELATION-ID", r.xCORRELATIONID, "simple", "")
	}
	if r.xAUTHUSERNAME != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-AUTH-USER-NAME", r.xAUTHUSERNAME, "simple", "")
	}
	// body params
	localVarPostBody = r.jsonPatchOperation
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 412 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v []Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
