/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
)

// OrderTermAction Future use, action to be taken when term expires
type OrderTermAction string

// List of Order_termAction
const (
	ORDERTERMACTION_ROLL OrderTermAction = "ROLL"
)

// All allowed values of OrderTermAction enum
var AllowedOrderTermActionEnumValues = []OrderTermAction{
	"ROLL",
}

func (v *OrderTermAction) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OrderTermAction(value)
	for _, existing := range AllowedOrderTermActionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OrderTermAction", value)
}

// NewOrderTermActionFromValue returns a pointer to a valid OrderTermAction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOrderTermActionFromValue(v string) (*OrderTermAction, error) {
	ev := OrderTermAction(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OrderTermAction: valid values are %v", v, AllowedOrderTermActionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OrderTermAction) IsValid() bool {
	for _, existing := range AllowedOrderTermActionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Order_termAction value
func (v OrderTermAction) Ptr() *OrderTermAction {
	return &v
}

type NullableOrderTermAction struct {
	value *OrderTermAction
	isSet bool
}

func (v NullableOrderTermAction) Get() *OrderTermAction {
	return v.value
}

func (v *NullableOrderTermAction) Set(val *OrderTermAction) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderTermAction) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderTermAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderTermAction(val *OrderTermAction) *NullableOrderTermAction {
	return &NullableOrderTermAction{value: val, isSet: true}
}

func (v NullableOrderTermAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderTermAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
