/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the ConnectionPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionPutRequest{}

// ConnectionPutRequest Create connection put request
type ConnectionPutRequest struct {
	Type *ConnectionType `json:"type,omitempty"`
	// Customer-provided connection name
	Name  *string `json:"name,omitempty"`
	Order *Order  `json:"order,omitempty"`
	// Preferences for notifications on connection configuration or status changes
	Notifications []SimplifiedNotification `json:"notifications,omitempty"`
	// Connection bandwidth in Mbps
	Bandwidth  *int32                `json:"bandwidth,omitempty"`
	Redundancy *ConnectionRedundancy `json:"redundancy,omitempty"`
	ASide      *ConnectionSide       `json:"aSide,omitempty"`
	ZSide      *ConnectionSide       `json:"zSide,omitempty"`
	Project    *Project              `json:"project,omitempty"`
	// Connection additional information
	AdditionalInfo       []ConnectionSideAdditionalInfo `json:"additionalInfo,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConnectionPutRequest ConnectionPutRequest

// NewConnectionPutRequest instantiates a new ConnectionPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionPutRequest() *ConnectionPutRequest {
	this := ConnectionPutRequest{}
	return &this
}

// NewConnectionPutRequestWithDefaults instantiates a new ConnectionPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionPutRequestWithDefaults() *ConnectionPutRequest {
	this := ConnectionPutRequest{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ConnectionPutRequest) GetType() ConnectionType {
	if o == nil || IsNil(o.Type) {
		var ret ConnectionType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionPutRequest) GetTypeOk() (*ConnectionType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ConnectionPutRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given ConnectionType and assigns it to the Type field.
func (o *ConnectionPutRequest) SetType(v ConnectionType) {
	o.Type = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ConnectionPutRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionPutRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ConnectionPutRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ConnectionPutRequest) SetName(v string) {
	o.Name = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *ConnectionPutRequest) GetOrder() Order {
	if o == nil || IsNil(o.Order) {
		var ret Order
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionPutRequest) GetOrderOk() (*Order, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *ConnectionPutRequest) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given Order and assigns it to the Order field.
func (o *ConnectionPutRequest) SetOrder(v Order) {
	o.Order = &v
}

// GetNotifications returns the Notifications field value if set, zero value otherwise.
func (o *ConnectionPutRequest) GetNotifications() []SimplifiedNotification {
	if o == nil || IsNil(o.Notifications) {
		var ret []SimplifiedNotification
		return ret
	}
	return o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionPutRequest) GetNotificationsOk() ([]SimplifiedNotification, bool) {
	if o == nil || IsNil(o.Notifications) {
		return nil, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *ConnectionPutRequest) HasNotifications() bool {
	if o != nil && !IsNil(o.Notifications) {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given []SimplifiedNotification and assigns it to the Notifications field.
func (o *ConnectionPutRequest) SetNotifications(v []SimplifiedNotification) {
	o.Notifications = v
}

// GetBandwidth returns the Bandwidth field value if set, zero value otherwise.
func (o *ConnectionPutRequest) GetBandwidth() int32 {
	if o == nil || IsNil(o.Bandwidth) {
		var ret int32
		return ret
	}
	return *o.Bandwidth
}

// GetBandwidthOk returns a tuple with the Bandwidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionPutRequest) GetBandwidthOk() (*int32, bool) {
	if o == nil || IsNil(o.Bandwidth) {
		return nil, false
	}
	return o.Bandwidth, true
}

// HasBandwidth returns a boolean if a field has been set.
func (o *ConnectionPutRequest) HasBandwidth() bool {
	if o != nil && !IsNil(o.Bandwidth) {
		return true
	}

	return false
}

// SetBandwidth gets a reference to the given int32 and assigns it to the Bandwidth field.
func (o *ConnectionPutRequest) SetBandwidth(v int32) {
	o.Bandwidth = &v
}

// GetRedundancy returns the Redundancy field value if set, zero value otherwise.
func (o *ConnectionPutRequest) GetRedundancy() ConnectionRedundancy {
	if o == nil || IsNil(o.Redundancy) {
		var ret ConnectionRedundancy
		return ret
	}
	return *o.Redundancy
}

// GetRedundancyOk returns a tuple with the Redundancy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionPutRequest) GetRedundancyOk() (*ConnectionRedundancy, bool) {
	if o == nil || IsNil(o.Redundancy) {
		return nil, false
	}
	return o.Redundancy, true
}

// HasRedundancy returns a boolean if a field has been set.
func (o *ConnectionPutRequest) HasRedundancy() bool {
	if o != nil && !IsNil(o.Redundancy) {
		return true
	}

	return false
}

// SetRedundancy gets a reference to the given ConnectionRedundancy and assigns it to the Redundancy field.
func (o *ConnectionPutRequest) SetRedundancy(v ConnectionRedundancy) {
	o.Redundancy = &v
}

// GetASide returns the ASide field value if set, zero value otherwise.
func (o *ConnectionPutRequest) GetASide() ConnectionSide {
	if o == nil || IsNil(o.ASide) {
		var ret ConnectionSide
		return ret
	}
	return *o.ASide
}

// GetASideOk returns a tuple with the ASide field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionPutRequest) GetASideOk() (*ConnectionSide, bool) {
	if o == nil || IsNil(o.ASide) {
		return nil, false
	}
	return o.ASide, true
}

// HasASide returns a boolean if a field has been set.
func (o *ConnectionPutRequest) HasASide() bool {
	if o != nil && !IsNil(o.ASide) {
		return true
	}

	return false
}

// SetASide gets a reference to the given ConnectionSide and assigns it to the ASide field.
func (o *ConnectionPutRequest) SetASide(v ConnectionSide) {
	o.ASide = &v
}

// GetZSide returns the ZSide field value if set, zero value otherwise.
func (o *ConnectionPutRequest) GetZSide() ConnectionSide {
	if o == nil || IsNil(o.ZSide) {
		var ret ConnectionSide
		return ret
	}
	return *o.ZSide
}

// GetZSideOk returns a tuple with the ZSide field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionPutRequest) GetZSideOk() (*ConnectionSide, bool) {
	if o == nil || IsNil(o.ZSide) {
		return nil, false
	}
	return o.ZSide, true
}

// HasZSide returns a boolean if a field has been set.
func (o *ConnectionPutRequest) HasZSide() bool {
	if o != nil && !IsNil(o.ZSide) {
		return true
	}

	return false
}

// SetZSide gets a reference to the given ConnectionSide and assigns it to the ZSide field.
func (o *ConnectionPutRequest) SetZSide(v ConnectionSide) {
	o.ZSide = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *ConnectionPutRequest) GetProject() Project {
	if o == nil || IsNil(o.Project) {
		var ret Project
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionPutRequest) GetProjectOk() (*Project, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *ConnectionPutRequest) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given Project and assigns it to the Project field.
func (o *ConnectionPutRequest) SetProject(v Project) {
	o.Project = &v
}

// GetAdditionalInfo returns the AdditionalInfo field value if set, zero value otherwise.
func (o *ConnectionPutRequest) GetAdditionalInfo() []ConnectionSideAdditionalInfo {
	if o == nil || IsNil(o.AdditionalInfo) {
		var ret []ConnectionSideAdditionalInfo
		return ret
	}
	return o.AdditionalInfo
}

// GetAdditionalInfoOk returns a tuple with the AdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionPutRequest) GetAdditionalInfoOk() ([]ConnectionSideAdditionalInfo, bool) {
	if o == nil || IsNil(o.AdditionalInfo) {
		return nil, false
	}
	return o.AdditionalInfo, true
}

// HasAdditionalInfo returns a boolean if a field has been set.
func (o *ConnectionPutRequest) HasAdditionalInfo() bool {
	if o != nil && !IsNil(o.AdditionalInfo) {
		return true
	}

	return false
}

// SetAdditionalInfo gets a reference to the given []ConnectionSideAdditionalInfo and assigns it to the AdditionalInfo field.
func (o *ConnectionPutRequest) SetAdditionalInfo(v []ConnectionSideAdditionalInfo) {
	o.AdditionalInfo = v
}

func (o ConnectionPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.Notifications) {
		toSerialize["notifications"] = o.Notifications
	}
	if !IsNil(o.Bandwidth) {
		toSerialize["bandwidth"] = o.Bandwidth
	}
	if !IsNil(o.Redundancy) {
		toSerialize["redundancy"] = o.Redundancy
	}
	if !IsNil(o.ASide) {
		toSerialize["aSide"] = o.ASide
	}
	if !IsNil(o.ZSide) {
		toSerialize["zSide"] = o.ZSide
	}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.AdditionalInfo) {
		toSerialize["additionalInfo"] = o.AdditionalInfo
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConnectionPutRequest) UnmarshalJSON(data []byte) (err error) {
	varConnectionPutRequest := _ConnectionPutRequest{}

	err = json.Unmarshal(data, &varConnectionPutRequest)

	if err != nil {
		return err
	}

	*o = ConnectionPutRequest(varConnectionPutRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "order")
		delete(additionalProperties, "notifications")
		delete(additionalProperties, "bandwidth")
		delete(additionalProperties, "redundancy")
		delete(additionalProperties, "aSide")
		delete(additionalProperties, "zSide")
		delete(additionalProperties, "project")
		delete(additionalProperties, "additionalInfo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectionPutRequest struct {
	value *ConnectionPutRequest
	isSet bool
}

func (v NullableConnectionPutRequest) Get() *ConnectionPutRequest {
	return v.value
}

func (v *NullableConnectionPutRequest) Set(val *ConnectionPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionPutRequest(val *ConnectionPutRequest) *NullableConnectionPutRequest {
	return &NullableConnectionPutRequest{value: val, isSet: true}
}

func (v NullableConnectionPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
