/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// Event - struct for Event
type Event struct {
	GetConnectionEvents       *GetConnectionEvents
	GetRpOperationStatusEvent *GetRpOperationStatusEvent
}

// GetConnectionEventsAsEvent is a convenience function that returns GetConnectionEvents wrapped in Event
func GetConnectionEventsAsEvent(v *GetConnectionEvents) Event {
	return Event{
		GetConnectionEvents: v,
	}
}

// GetRpOperationStatusEventAsEvent is a convenience function that returns GetRpOperationStatusEvent wrapped in Event
func GetRpOperationStatusEventAsEvent(v *GetRpOperationStatusEvent) Event {
	return Event{
		GetRpOperationStatusEvent: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *Event) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into GetConnectionEvents
	err = newStrictDecoder(data).Decode(&dst.GetConnectionEvents)
	if err == nil {
		jsonGetConnectionEvents, _ := json.Marshal(dst.GetConnectionEvents)
		if string(jsonGetConnectionEvents) == "{}" { // empty struct
			dst.GetConnectionEvents = nil
		} else {
			if err = validator.Validate(dst.GetConnectionEvents); err != nil {
				dst.GetConnectionEvents = nil
			} else {
				match++
			}
		}
	} else {
		dst.GetConnectionEvents = nil
	}

	// try to unmarshal data into GetRpOperationStatusEvent
	err = newStrictDecoder(data).Decode(&dst.GetRpOperationStatusEvent)
	if err == nil {
		jsonGetRpOperationStatusEvent, _ := json.Marshal(dst.GetRpOperationStatusEvent)
		if string(jsonGetRpOperationStatusEvent) == "{}" { // empty struct
			dst.GetRpOperationStatusEvent = nil
		} else {
			if err = validator.Validate(dst.GetRpOperationStatusEvent); err != nil {
				dst.GetRpOperationStatusEvent = nil
			} else {
				match++
			}
		}
	} else {
		dst.GetRpOperationStatusEvent = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.GetConnectionEvents = nil
		dst.GetRpOperationStatusEvent = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Event)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Event)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Event) MarshalJSON() ([]byte, error) {
	if src.GetConnectionEvents != nil {
		return json.Marshal(&src.GetConnectionEvents)
	}

	if src.GetRpOperationStatusEvent != nil {
		return json.Marshal(&src.GetRpOperationStatusEvent)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Event) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.GetConnectionEvents != nil {
		return obj.GetConnectionEvents
	}

	if obj.GetRpOperationStatusEvent != nil {
		return obj.GetRpOperationStatusEvent
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Event) GetActualInstanceValue() interface{} {
	if obj.GetConnectionEvents != nil {
		return *obj.GetConnectionEvents
	}

	if obj.GetRpOperationStatusEvent != nil {
		return *obj.GetRpOperationStatusEvent
	}

	// all schemas are nil
	return nil
}

type NullableEvent struct {
	value *Event
	isSet bool
}

func (v NullableEvent) Get() *Event {
	return v.value
}

func (v *NullableEvent) Set(val *Event) {
	v.value = val
	v.isSet = true
}

func (v NullableEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvent(val *Event) *NullableEvent {
	return &NullableEvent{value: val, isSet: true}
}

func (v NullableEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
