/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the ConnectionBulk type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionBulk{}

// ConnectionBulk Bulk Connection specification
type ConnectionBulk struct {
	Data                 []Connection `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConnectionBulk ConnectionBulk

// NewConnectionBulk instantiates a new ConnectionBulk object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionBulk() *ConnectionBulk {
	this := ConnectionBulk{}
	return &this
}

// NewConnectionBulkWithDefaults instantiates a new ConnectionBulk object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionBulkWithDefaults() *ConnectionBulk {
	this := ConnectionBulk{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ConnectionBulk) GetData() []Connection {
	if o == nil || IsNil(o.Data) {
		var ret []Connection
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionBulk) GetDataOk() ([]Connection, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ConnectionBulk) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Connection and assigns it to the Data field.
func (o *ConnectionBulk) SetData(v []Connection) {
	o.Data = v
}

func (o ConnectionBulk) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionBulk) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConnectionBulk) UnmarshalJSON(data []byte) (err error) {
	varConnectionBulk := _ConnectionBulk{}

	err = json.Unmarshal(data, &varConnectionBulk)

	if err != nil {
		return err
	}

	*o = ConnectionBulk(varConnectionBulk)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectionBulk struct {
	value *ConnectionBulk
	isSet bool
}

func (v NullableConnectionBulk) Get() *ConnectionBulk {
	return v.value
}

func (v *NullableConnectionBulk) Set(val *ConnectionBulk) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionBulk) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionBulk) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionBulk(val *ConnectionBulk) *NullableConnectionBulk {
	return &NullableConnectionBulk{value: val, isSet: true}
}

func (v NullableConnectionBulk) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionBulk) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
