/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"time"
)

// checks if the ConnectionTransaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionTransaction{}

// ConnectionTransaction struct for ConnectionTransaction
type ConnectionTransaction struct {
	// transaction type
	Type *string `json:"type,omitempty"`
	// transaction state
	State *string `json:"state,omitempty"`
	// Created by Date and Time
	InitiatedDateTime *time.Time `json:"initiatedDateTime,omitempty"`
	// duration
	Duration *string `json:"duration,omitempty"`
	// for internal users
	DurationSlo          *string           `json:"durationSlo,omitempty"`
	Stage                *TransactionStage `json:"stage,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConnectionTransaction ConnectionTransaction

// NewConnectionTransaction instantiates a new ConnectionTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionTransaction() *ConnectionTransaction {
	this := ConnectionTransaction{}
	return &this
}

// NewConnectionTransactionWithDefaults instantiates a new ConnectionTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionTransactionWithDefaults() *ConnectionTransaction {
	this := ConnectionTransaction{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ConnectionTransaction) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionTransaction) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ConnectionTransaction) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ConnectionTransaction) SetType(v string) {
	o.Type = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ConnectionTransaction) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionTransaction) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ConnectionTransaction) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ConnectionTransaction) SetState(v string) {
	o.State = &v
}

// GetInitiatedDateTime returns the InitiatedDateTime field value if set, zero value otherwise.
func (o *ConnectionTransaction) GetInitiatedDateTime() time.Time {
	if o == nil || IsNil(o.InitiatedDateTime) {
		var ret time.Time
		return ret
	}
	return *o.InitiatedDateTime
}

// GetInitiatedDateTimeOk returns a tuple with the InitiatedDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionTransaction) GetInitiatedDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.InitiatedDateTime) {
		return nil, false
	}
	return o.InitiatedDateTime, true
}

// HasInitiatedDateTime returns a boolean if a field has been set.
func (o *ConnectionTransaction) HasInitiatedDateTime() bool {
	if o != nil && !IsNil(o.InitiatedDateTime) {
		return true
	}

	return false
}

// SetInitiatedDateTime gets a reference to the given time.Time and assigns it to the InitiatedDateTime field.
func (o *ConnectionTransaction) SetInitiatedDateTime(v time.Time) {
	o.InitiatedDateTime = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *ConnectionTransaction) GetDuration() string {
	if o == nil || IsNil(o.Duration) {
		var ret string
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionTransaction) GetDurationOk() (*string, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *ConnectionTransaction) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given string and assigns it to the Duration field.
func (o *ConnectionTransaction) SetDuration(v string) {
	o.Duration = &v
}

// GetDurationSlo returns the DurationSlo field value if set, zero value otherwise.
func (o *ConnectionTransaction) GetDurationSlo() string {
	if o == nil || IsNil(o.DurationSlo) {
		var ret string
		return ret
	}
	return *o.DurationSlo
}

// GetDurationSloOk returns a tuple with the DurationSlo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionTransaction) GetDurationSloOk() (*string, bool) {
	if o == nil || IsNil(o.DurationSlo) {
		return nil, false
	}
	return o.DurationSlo, true
}

// HasDurationSlo returns a boolean if a field has been set.
func (o *ConnectionTransaction) HasDurationSlo() bool {
	if o != nil && !IsNil(o.DurationSlo) {
		return true
	}

	return false
}

// SetDurationSlo gets a reference to the given string and assigns it to the DurationSlo field.
func (o *ConnectionTransaction) SetDurationSlo(v string) {
	o.DurationSlo = &v
}

// GetStage returns the Stage field value if set, zero value otherwise.
func (o *ConnectionTransaction) GetStage() TransactionStage {
	if o == nil || IsNil(o.Stage) {
		var ret TransactionStage
		return ret
	}
	return *o.Stage
}

// GetStageOk returns a tuple with the Stage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionTransaction) GetStageOk() (*TransactionStage, bool) {
	if o == nil || IsNil(o.Stage) {
		return nil, false
	}
	return o.Stage, true
}

// HasStage returns a boolean if a field has been set.
func (o *ConnectionTransaction) HasStage() bool {
	if o != nil && !IsNil(o.Stage) {
		return true
	}

	return false
}

// SetStage gets a reference to the given TransactionStage and assigns it to the Stage field.
func (o *ConnectionTransaction) SetStage(v TransactionStage) {
	o.Stage = &v
}

func (o ConnectionTransaction) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionTransaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.InitiatedDateTime) {
		toSerialize["initiatedDateTime"] = o.InitiatedDateTime
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.DurationSlo) {
		toSerialize["durationSlo"] = o.DurationSlo
	}
	if !IsNil(o.Stage) {
		toSerialize["stage"] = o.Stage
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConnectionTransaction) UnmarshalJSON(data []byte) (err error) {
	varConnectionTransaction := _ConnectionTransaction{}

	err = json.Unmarshal(data, &varConnectionTransaction)

	if err != nil {
		return err
	}

	*o = ConnectionTransaction(varConnectionTransaction)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "state")
		delete(additionalProperties, "initiatedDateTime")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "durationSlo")
		delete(additionalProperties, "stage")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectionTransaction struct {
	value *ConnectionTransaction
	isSet bool
}

func (v NullableConnectionTransaction) Get() *ConnectionTransaction {
	return v.value
}

func (v *NullableConnectionTransaction) Set(val *ConnectionTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionTransaction(val *ConnectionTransaction) *NullableConnectionTransaction {
	return &NullableConnectionTransaction{value: val, isSet: true}
}

func (v NullableConnectionTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
