/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the GetConnectionEvents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetConnectionEvents{}

// GetConnectionEvents struct for GetConnectionEvents
type GetConnectionEvents struct {
	// Connection additional information
	AdditionalInfo       []AdditionalInfoProperty `json:"additionalInfo,omitempty"`
	Connection           *EventConnection         `json:"connection,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetConnectionEvents GetConnectionEvents

// NewGetConnectionEvents instantiates a new GetConnectionEvents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConnectionEvents() *GetConnectionEvents {
	this := GetConnectionEvents{}
	return &this
}

// NewGetConnectionEventsWithDefaults instantiates a new GetConnectionEvents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConnectionEventsWithDefaults() *GetConnectionEvents {
	this := GetConnectionEvents{}
	return &this
}

// GetAdditionalInfo returns the AdditionalInfo field value if set, zero value otherwise.
func (o *GetConnectionEvents) GetAdditionalInfo() []AdditionalInfoProperty {
	if o == nil || IsNil(o.AdditionalInfo) {
		var ret []AdditionalInfoProperty
		return ret
	}
	return o.AdditionalInfo
}

// GetAdditionalInfoOk returns a tuple with the AdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectionEvents) GetAdditionalInfoOk() ([]AdditionalInfoProperty, bool) {
	if o == nil || IsNil(o.AdditionalInfo) {
		return nil, false
	}
	return o.AdditionalInfo, true
}

// HasAdditionalInfo returns a boolean if a field has been set.
func (o *GetConnectionEvents) HasAdditionalInfo() bool {
	if o != nil && !IsNil(o.AdditionalInfo) {
		return true
	}

	return false
}

// SetAdditionalInfo gets a reference to the given []AdditionalInfoProperty and assigns it to the AdditionalInfo field.
func (o *GetConnectionEvents) SetAdditionalInfo(v []AdditionalInfoProperty) {
	o.AdditionalInfo = v
}

// GetConnection returns the Connection field value if set, zero value otherwise.
func (o *GetConnectionEvents) GetConnection() EventConnection {
	if o == nil || IsNil(o.Connection) {
		var ret EventConnection
		return ret
	}
	return *o.Connection
}

// GetConnectionOk returns a tuple with the Connection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectionEvents) GetConnectionOk() (*EventConnection, bool) {
	if o == nil || IsNil(o.Connection) {
		return nil, false
	}
	return o.Connection, true
}

// HasConnection returns a boolean if a field has been set.
func (o *GetConnectionEvents) HasConnection() bool {
	if o != nil && !IsNil(o.Connection) {
		return true
	}

	return false
}

// SetConnection gets a reference to the given EventConnection and assigns it to the Connection field.
func (o *GetConnectionEvents) SetConnection(v EventConnection) {
	o.Connection = &v
}

func (o GetConnectionEvents) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetConnectionEvents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdditionalInfo) {
		toSerialize["additionalInfo"] = o.AdditionalInfo
	}
	if !IsNil(o.Connection) {
		toSerialize["connection"] = o.Connection
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetConnectionEvents) UnmarshalJSON(data []byte) (err error) {
	varGetConnectionEvents := _GetConnectionEvents{}

	err = json.Unmarshal(data, &varGetConnectionEvents)

	if err != nil {
		return err
	}

	*o = GetConnectionEvents(varGetConnectionEvents)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "additionalInfo")
		delete(additionalProperties, "connection")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetConnectionEvents struct {
	value *GetConnectionEvents
	isSet bool
}

func (v NullableGetConnectionEvents) Get() *GetConnectionEvents {
	return v.value
}

func (v *NullableGetConnectionEvents) Set(val *GetConnectionEvents) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConnectionEvents) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConnectionEvents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConnectionEvents(val *GetConnectionEvents) *NullableGetConnectionEvents {
	return &NullableGetConnectionEvents{value: val, isSet: true}
}

func (v NullableGetConnectionEvents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConnectionEvents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
