/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
)

// ConnectionSideDataPlane Data plane
type ConnectionSideDataPlane string

// List of ConnectionSide_dataPlane
const (
	CONNECTIONSIDEDATAPLANE_BLUE ConnectionSideDataPlane = "BLUE"
	CONNECTIONSIDEDATAPLANE_RED  ConnectionSideDataPlane = "RED"
)

// All allowed values of ConnectionSideDataPlane enum
var AllowedConnectionSideDataPlaneEnumValues = []ConnectionSideDataPlane{
	"BLUE",
	"RED",
}

func (v *ConnectionSideDataPlane) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ConnectionSideDataPlane(value)
	for _, existing := range AllowedConnectionSideDataPlaneEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ConnectionSideDataPlane", value)
}

// NewConnectionSideDataPlaneFromValue returns a pointer to a valid ConnectionSideDataPlane
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewConnectionSideDataPlaneFromValue(v string) (*ConnectionSideDataPlane, error) {
	ev := ConnectionSideDataPlane(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ConnectionSideDataPlane: valid values are %v", v, AllowedConnectionSideDataPlaneEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ConnectionSideDataPlane) IsValid() bool {
	for _, existing := range AllowedConnectionSideDataPlaneEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ConnectionSide_dataPlane value
func (v ConnectionSideDataPlane) Ptr() *ConnectionSideDataPlane {
	return &v
}

type NullableConnectionSideDataPlane struct {
	value *ConnectionSideDataPlane
	isSet bool
}

func (v NullableConnectionSideDataPlane) Get() *ConnectionSideDataPlane {
	return v.value
}

func (v *NullableConnectionSideDataPlane) Set(val *ConnectionSideDataPlane) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionSideDataPlane) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionSideDataPlane) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionSideDataPlane(val *ConnectionSideDataPlane) *NullableConnectionSideDataPlane {
	return &NullableConnectionSideDataPlane{value: val, isSet: true}
}

func (v NullableConnectionSideDataPlane) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionSideDataPlane) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
