/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
)

// GetEventTypeParameter the model 'GetEventTypeParameter'
type GetEventTypeParameter string

// List of getEvent_type_parameter
const (
	GETEVENTTYPEPARAMETER_TRANSACTION_STATUS_AUDIT GetEventTypeParameter = "TRANSACTION_STATUS_AUDIT"
	GETEVENTTYPEPARAMETER_RP_OPSTATUS_NOTIFICATION GetEventTypeParameter = "RP_OPSTATUS_NOTIFICATION"
	GETEVENTTYPEPARAMETER_RP_CONFIG_NOTIFICATION   GetEventTypeParameter = "RP_CONFIG_NOTIFICATION"
)

// All allowed values of GetEventTypeParameter enum
var AllowedGetEventTypeParameterEnumValues = []GetEventTypeParameter{
	"TRANSACTION_STATUS_AUDIT",
	"RP_OPSTATUS_NOTIFICATION",
	"RP_CONFIG_NOTIFICATION",
}

func (v *GetEventTypeParameter) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GetEventTypeParameter(value)
	for _, existing := range AllowedGetEventTypeParameterEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GetEventTypeParameter", value)
}

// NewGetEventTypeParameterFromValue returns a pointer to a valid GetEventTypeParameter
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGetEventTypeParameterFromValue(v string) (*GetEventTypeParameter, error) {
	ev := GetEventTypeParameter(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GetEventTypeParameter: valid values are %v", v, AllowedGetEventTypeParameterEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GetEventTypeParameter) IsValid() bool {
	for _, existing := range AllowedGetEventTypeParameterEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to getEvent_type_parameter value
func (v GetEventTypeParameter) Ptr() *GetEventTypeParameter {
	return &v
}

type NullableGetEventTypeParameter struct {
	value *GetEventTypeParameter
	isSet bool
}

func (v NullableGetEventTypeParameter) Get() *GetEventTypeParameter {
	return v.value
}

func (v *NullableGetEventTypeParameter) Set(val *GetEventTypeParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEventTypeParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEventTypeParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEventTypeParameter(val *GetEventTypeParameter) *NullableGetEventTypeParameter {
	return &NullableGetEventTypeParameter{value: val, isSet: true}
}

func (v NullableGetEventTypeParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEventTypeParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
