/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
)

// GetRpOperationStatusEventSubType the model 'GetRpOperationStatusEventSubType'
type GetRpOperationStatusEventSubType string

// List of get_rp_operation_status_event_subType
const (
	GETRPOPERATIONSTATUSEVENTSUBTYPE_BGP_IPV4_STATE_CHANGE                           GetRpOperationStatusEventSubType = "BGP_IPV4_STATE_CHANGE"
	GETRPOPERATIONSTATUSEVENTSUBTYPE_BGP_IPV4_ADMIN_ENABLE                           GetRpOperationStatusEventSubType = "BGP_IPV4_ADMIN_ENABLE"
	GETRPOPERATIONSTATUSEVENTSUBTYPE_BGP_IPV4_NEIGHBOR_RESET                         GetRpOperationStatusEventSubType = "BGP_IPV4_NEIGHBOR_RESET"
	GETRPOPERATIONSTATUSEVENTSUBTYPE_CLOUD_ROUTER_IPV4_ROUTE_USAGE_REACHED_LIMIT     GetRpOperationStatusEventSubType = "CLOUD_ROUTER_IPV4_ROUTE_USAGE_REACHED_LIMIT"
	GETRPOPERATIONSTATUSEVENTSUBTYPE_CLOUD_ROUTER_IPV6_ROUTE_USAGE_REACHED_LIMIT     GetRpOperationStatusEventSubType = "CLOUD_ROUTER_IPV6_ROUTE_USAGE_REACHED_LIMIT"
	GETRPOPERATIONSTATUSEVENTSUBTYPE_CLOUD_ROUTER_IPV4_ROUTE_USAGE_REACHED_THRESHOLD GetRpOperationStatusEventSubType = "CLOUD_ROUTER_IPV4_ROUTE_USAGE_REACHED_THRESHOLD"
	GETRPOPERATIONSTATUSEVENTSUBTYPE_CLOUD_ROUTER_IPV6_ROUTE_USAGE_REACHED_THRESHOLD GetRpOperationStatusEventSubType = "CLOUD_ROUTER_IPV6_ROUTE_USAGE_REACHED_THRESHOLD"
)

// All allowed values of GetRpOperationStatusEventSubType enum
var AllowedGetRpOperationStatusEventSubTypeEnumValues = []GetRpOperationStatusEventSubType{
	"BGP_IPV4_STATE_CHANGE",
	"BGP_IPV4_ADMIN_ENABLE",
	"BGP_IPV4_NEIGHBOR_RESET",
	"CLOUD_ROUTER_IPV4_ROUTE_USAGE_REACHED_LIMIT",
	"CLOUD_ROUTER_IPV6_ROUTE_USAGE_REACHED_LIMIT",
	"CLOUD_ROUTER_IPV4_ROUTE_USAGE_REACHED_THRESHOLD",
	"CLOUD_ROUTER_IPV6_ROUTE_USAGE_REACHED_THRESHOLD",
}

func (v *GetRpOperationStatusEventSubType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GetRpOperationStatusEventSubType(value)
	for _, existing := range AllowedGetRpOperationStatusEventSubTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GetRpOperationStatusEventSubType", value)
}

// NewGetRpOperationStatusEventSubTypeFromValue returns a pointer to a valid GetRpOperationStatusEventSubType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGetRpOperationStatusEventSubTypeFromValue(v string) (*GetRpOperationStatusEventSubType, error) {
	ev := GetRpOperationStatusEventSubType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GetRpOperationStatusEventSubType: valid values are %v", v, AllowedGetRpOperationStatusEventSubTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GetRpOperationStatusEventSubType) IsValid() bool {
	for _, existing := range AllowedGetRpOperationStatusEventSubTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to get_rp_operation_status_event_subType value
func (v GetRpOperationStatusEventSubType) Ptr() *GetRpOperationStatusEventSubType {
	return &v
}

type NullableGetRpOperationStatusEventSubType struct {
	value *GetRpOperationStatusEventSubType
	isSet bool
}

func (v NullableGetRpOperationStatusEventSubType) Get() *GetRpOperationStatusEventSubType {
	return v.value
}

func (v *NullableGetRpOperationStatusEventSubType) Set(val *GetRpOperationStatusEventSubType) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRpOperationStatusEventSubType) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRpOperationStatusEventSubType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRpOperationStatusEventSubType(val *GetRpOperationStatusEventSubType) *NullableGetRpOperationStatusEventSubType {
	return &NullableGetRpOperationStatusEventSubType{value: val, isSet: true}
}

func (v NullableGetRpOperationStatusEventSubType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRpOperationStatusEventSubType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
