/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the ConnectionBulkPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionBulkPostRequest{}

// ConnectionBulkPostRequest Create bulk connection post request
type ConnectionBulkPostRequest struct {
	Data                 []ConnectionPostRequest `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConnectionBulkPostRequest ConnectionBulkPostRequest

// NewConnectionBulkPostRequest instantiates a new ConnectionBulkPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionBulkPostRequest() *ConnectionBulkPostRequest {
	this := ConnectionBulkPostRequest{}
	return &this
}

// NewConnectionBulkPostRequestWithDefaults instantiates a new ConnectionBulkPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionBulkPostRequestWithDefaults() *ConnectionBulkPostRequest {
	this := ConnectionBulkPostRequest{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ConnectionBulkPostRequest) GetData() []ConnectionPostRequest {
	if o == nil || IsNil(o.Data) {
		var ret []ConnectionPostRequest
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionBulkPostRequest) GetDataOk() ([]ConnectionPostRequest, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ConnectionBulkPostRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ConnectionPostRequest and assigns it to the Data field.
func (o *ConnectionBulkPostRequest) SetData(v []ConnectionPostRequest) {
	o.Data = v
}

func (o ConnectionBulkPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionBulkPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConnectionBulkPostRequest) UnmarshalJSON(data []byte) (err error) {
	varConnectionBulkPostRequest := _ConnectionBulkPostRequest{}

	err = json.Unmarshal(data, &varConnectionBulkPostRequest)

	if err != nil {
		return err
	}

	*o = ConnectionBulkPostRequest(varConnectionBulkPostRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectionBulkPostRequest struct {
	value *ConnectionBulkPostRequest
	isSet bool
}

func (v NullableConnectionBulkPostRequest) Get() *ConnectionBulkPostRequest {
	return v.value
}

func (v *NullableConnectionBulkPostRequest) Set(val *ConnectionBulkPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionBulkPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionBulkPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionBulkPostRequest(val *ConnectionBulkPostRequest) *NullableConnectionBulkPostRequest {
	return &NullableConnectionBulkPostRequest{value: val, isSet: true}
}

func (v NullableConnectionBulkPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionBulkPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
