/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the SimplifiedLinkProtocol type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SimplifiedLinkProtocol{}

// SimplifiedLinkProtocol Connection link protocol Configuration
type SimplifiedLinkProtocol struct {
	Type *LinkProtocolType `json:"type,omitempty"`
	// vlanTag value specified for DOT1Q connections
	VlanTag *int32 `json:"vlanTag,omitempty"`
	// vlanTag Min value specified for DOT1Q connections
	VlanTagMin *int32 `json:"vlanTagMin,omitempty"`
	// vlanTag Max value specified for DOT1Q connections
	VlanTagMax *int32 `json:"vlanTagMax,omitempty"`
	// vlanSTag value specified for QINQ connections
	VlanSTag *int32 `json:"vlanSTag,omitempty"`
	// vlanCTag value specified for QINQ connections
	VlanCTag *int32 `json:"vlanCTag,omitempty"`
	// vlanCTag Minvalue specified for QINQ connections
	VlanCTagMin *int32 `json:"vlanCTagMin,omitempty"`
	// vlanCTag max value specified for QINQ connections
	VlanCTagMax          *int32 `json:"vlanCTagMax,omitempty"`
	Unit                 *int32 `json:"unit,omitempty"`
	Vni                  *int32 `json:"vni,omitempty"`
	IntUnit              *int32 `json:"intUnit,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SimplifiedLinkProtocol SimplifiedLinkProtocol

// NewSimplifiedLinkProtocol instantiates a new SimplifiedLinkProtocol object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSimplifiedLinkProtocol() *SimplifiedLinkProtocol {
	this := SimplifiedLinkProtocol{}
	return &this
}

// NewSimplifiedLinkProtocolWithDefaults instantiates a new SimplifiedLinkProtocol object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSimplifiedLinkProtocolWithDefaults() *SimplifiedLinkProtocol {
	this := SimplifiedLinkProtocol{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SimplifiedLinkProtocol) GetType() LinkProtocolType {
	if o == nil || IsNil(o.Type) {
		var ret LinkProtocolType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplifiedLinkProtocol) GetTypeOk() (*LinkProtocolType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SimplifiedLinkProtocol) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given LinkProtocolType and assigns it to the Type field.
func (o *SimplifiedLinkProtocol) SetType(v LinkProtocolType) {
	o.Type = &v
}

// GetVlanTag returns the VlanTag field value if set, zero value otherwise.
func (o *SimplifiedLinkProtocol) GetVlanTag() int32 {
	if o == nil || IsNil(o.VlanTag) {
		var ret int32
		return ret
	}
	return *o.VlanTag
}

// GetVlanTagOk returns a tuple with the VlanTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplifiedLinkProtocol) GetVlanTagOk() (*int32, bool) {
	if o == nil || IsNil(o.VlanTag) {
		return nil, false
	}
	return o.VlanTag, true
}

// HasVlanTag returns a boolean if a field has been set.
func (o *SimplifiedLinkProtocol) HasVlanTag() bool {
	if o != nil && !IsNil(o.VlanTag) {
		return true
	}

	return false
}

// SetVlanTag gets a reference to the given int32 and assigns it to the VlanTag field.
func (o *SimplifiedLinkProtocol) SetVlanTag(v int32) {
	o.VlanTag = &v
}

// GetVlanTagMin returns the VlanTagMin field value if set, zero value otherwise.
func (o *SimplifiedLinkProtocol) GetVlanTagMin() int32 {
	if o == nil || IsNil(o.VlanTagMin) {
		var ret int32
		return ret
	}
	return *o.VlanTagMin
}

// GetVlanTagMinOk returns a tuple with the VlanTagMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplifiedLinkProtocol) GetVlanTagMinOk() (*int32, bool) {
	if o == nil || IsNil(o.VlanTagMin) {
		return nil, false
	}
	return o.VlanTagMin, true
}

// HasVlanTagMin returns a boolean if a field has been set.
func (o *SimplifiedLinkProtocol) HasVlanTagMin() bool {
	if o != nil && !IsNil(o.VlanTagMin) {
		return true
	}

	return false
}

// SetVlanTagMin gets a reference to the given int32 and assigns it to the VlanTagMin field.
func (o *SimplifiedLinkProtocol) SetVlanTagMin(v int32) {
	o.VlanTagMin = &v
}

// GetVlanTagMax returns the VlanTagMax field value if set, zero value otherwise.
func (o *SimplifiedLinkProtocol) GetVlanTagMax() int32 {
	if o == nil || IsNil(o.VlanTagMax) {
		var ret int32
		return ret
	}
	return *o.VlanTagMax
}

// GetVlanTagMaxOk returns a tuple with the VlanTagMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplifiedLinkProtocol) GetVlanTagMaxOk() (*int32, bool) {
	if o == nil || IsNil(o.VlanTagMax) {
		return nil, false
	}
	return o.VlanTagMax, true
}

// HasVlanTagMax returns a boolean if a field has been set.
func (o *SimplifiedLinkProtocol) HasVlanTagMax() bool {
	if o != nil && !IsNil(o.VlanTagMax) {
		return true
	}

	return false
}

// SetVlanTagMax gets a reference to the given int32 and assigns it to the VlanTagMax field.
func (o *SimplifiedLinkProtocol) SetVlanTagMax(v int32) {
	o.VlanTagMax = &v
}

// GetVlanSTag returns the VlanSTag field value if set, zero value otherwise.
func (o *SimplifiedLinkProtocol) GetVlanSTag() int32 {
	if o == nil || IsNil(o.VlanSTag) {
		var ret int32
		return ret
	}
	return *o.VlanSTag
}

// GetVlanSTagOk returns a tuple with the VlanSTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplifiedLinkProtocol) GetVlanSTagOk() (*int32, bool) {
	if o == nil || IsNil(o.VlanSTag) {
		return nil, false
	}
	return o.VlanSTag, true
}

// HasVlanSTag returns a boolean if a field has been set.
func (o *SimplifiedLinkProtocol) HasVlanSTag() bool {
	if o != nil && !IsNil(o.VlanSTag) {
		return true
	}

	return false
}

// SetVlanSTag gets a reference to the given int32 and assigns it to the VlanSTag field.
func (o *SimplifiedLinkProtocol) SetVlanSTag(v int32) {
	o.VlanSTag = &v
}

// GetVlanCTag returns the VlanCTag field value if set, zero value otherwise.
func (o *SimplifiedLinkProtocol) GetVlanCTag() int32 {
	if o == nil || IsNil(o.VlanCTag) {
		var ret int32
		return ret
	}
	return *o.VlanCTag
}

// GetVlanCTagOk returns a tuple with the VlanCTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplifiedLinkProtocol) GetVlanCTagOk() (*int32, bool) {
	if o == nil || IsNil(o.VlanCTag) {
		return nil, false
	}
	return o.VlanCTag, true
}

// HasVlanCTag returns a boolean if a field has been set.
func (o *SimplifiedLinkProtocol) HasVlanCTag() bool {
	if o != nil && !IsNil(o.VlanCTag) {
		return true
	}

	return false
}

// SetVlanCTag gets a reference to the given int32 and assigns it to the VlanCTag field.
func (o *SimplifiedLinkProtocol) SetVlanCTag(v int32) {
	o.VlanCTag = &v
}

// GetVlanCTagMin returns the VlanCTagMin field value if set, zero value otherwise.
func (o *SimplifiedLinkProtocol) GetVlanCTagMin() int32 {
	if o == nil || IsNil(o.VlanCTagMin) {
		var ret int32
		return ret
	}
	return *o.VlanCTagMin
}

// GetVlanCTagMinOk returns a tuple with the VlanCTagMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplifiedLinkProtocol) GetVlanCTagMinOk() (*int32, bool) {
	if o == nil || IsNil(o.VlanCTagMin) {
		return nil, false
	}
	return o.VlanCTagMin, true
}

// HasVlanCTagMin returns a boolean if a field has been set.
func (o *SimplifiedLinkProtocol) HasVlanCTagMin() bool {
	if o != nil && !IsNil(o.VlanCTagMin) {
		return true
	}

	return false
}

// SetVlanCTagMin gets a reference to the given int32 and assigns it to the VlanCTagMin field.
func (o *SimplifiedLinkProtocol) SetVlanCTagMin(v int32) {
	o.VlanCTagMin = &v
}

// GetVlanCTagMax returns the VlanCTagMax field value if set, zero value otherwise.
func (o *SimplifiedLinkProtocol) GetVlanCTagMax() int32 {
	if o == nil || IsNil(o.VlanCTagMax) {
		var ret int32
		return ret
	}
	return *o.VlanCTagMax
}

// GetVlanCTagMaxOk returns a tuple with the VlanCTagMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplifiedLinkProtocol) GetVlanCTagMaxOk() (*int32, bool) {
	if o == nil || IsNil(o.VlanCTagMax) {
		return nil, false
	}
	return o.VlanCTagMax, true
}

// HasVlanCTagMax returns a boolean if a field has been set.
func (o *SimplifiedLinkProtocol) HasVlanCTagMax() bool {
	if o != nil && !IsNil(o.VlanCTagMax) {
		return true
	}

	return false
}

// SetVlanCTagMax gets a reference to the given int32 and assigns it to the VlanCTagMax field.
func (o *SimplifiedLinkProtocol) SetVlanCTagMax(v int32) {
	o.VlanCTagMax = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *SimplifiedLinkProtocol) GetUnit() int32 {
	if o == nil || IsNil(o.Unit) {
		var ret int32
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplifiedLinkProtocol) GetUnitOk() (*int32, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *SimplifiedLinkProtocol) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given int32 and assigns it to the Unit field.
func (o *SimplifiedLinkProtocol) SetUnit(v int32) {
	o.Unit = &v
}

// GetVni returns the Vni field value if set, zero value otherwise.
func (o *SimplifiedLinkProtocol) GetVni() int32 {
	if o == nil || IsNil(o.Vni) {
		var ret int32
		return ret
	}
	return *o.Vni
}

// GetVniOk returns a tuple with the Vni field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplifiedLinkProtocol) GetVniOk() (*int32, bool) {
	if o == nil || IsNil(o.Vni) {
		return nil, false
	}
	return o.Vni, true
}

// HasVni returns a boolean if a field has been set.
func (o *SimplifiedLinkProtocol) HasVni() bool {
	if o != nil && !IsNil(o.Vni) {
		return true
	}

	return false
}

// SetVni gets a reference to the given int32 and assigns it to the Vni field.
func (o *SimplifiedLinkProtocol) SetVni(v int32) {
	o.Vni = &v
}

// GetIntUnit returns the IntUnit field value if set, zero value otherwise.
func (o *SimplifiedLinkProtocol) GetIntUnit() int32 {
	if o == nil || IsNil(o.IntUnit) {
		var ret int32
		return ret
	}
	return *o.IntUnit
}

// GetIntUnitOk returns a tuple with the IntUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplifiedLinkProtocol) GetIntUnitOk() (*int32, bool) {
	if o == nil || IsNil(o.IntUnit) {
		return nil, false
	}
	return o.IntUnit, true
}

// HasIntUnit returns a boolean if a field has been set.
func (o *SimplifiedLinkProtocol) HasIntUnit() bool {
	if o != nil && !IsNil(o.IntUnit) {
		return true
	}

	return false
}

// SetIntUnit gets a reference to the given int32 and assigns it to the IntUnit field.
func (o *SimplifiedLinkProtocol) SetIntUnit(v int32) {
	o.IntUnit = &v
}

func (o SimplifiedLinkProtocol) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SimplifiedLinkProtocol) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.VlanTag) {
		toSerialize["vlanTag"] = o.VlanTag
	}
	if !IsNil(o.VlanTagMin) {
		toSerialize["vlanTagMin"] = o.VlanTagMin
	}
	if !IsNil(o.VlanTagMax) {
		toSerialize["vlanTagMax"] = o.VlanTagMax
	}
	if !IsNil(o.VlanSTag) {
		toSerialize["vlanSTag"] = o.VlanSTag
	}
	if !IsNil(o.VlanCTag) {
		toSerialize["vlanCTag"] = o.VlanCTag
	}
	if !IsNil(o.VlanCTagMin) {
		toSerialize["vlanCTagMin"] = o.VlanCTagMin
	}
	if !IsNil(o.VlanCTagMax) {
		toSerialize["vlanCTagMax"] = o.VlanCTagMax
	}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	if !IsNil(o.Vni) {
		toSerialize["vni"] = o.Vni
	}
	if !IsNil(o.IntUnit) {
		toSerialize["intUnit"] = o.IntUnit
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SimplifiedLinkProtocol) UnmarshalJSON(data []byte) (err error) {
	varSimplifiedLinkProtocol := _SimplifiedLinkProtocol{}

	err = json.Unmarshal(data, &varSimplifiedLinkProtocol)

	if err != nil {
		return err
	}

	*o = SimplifiedLinkProtocol(varSimplifiedLinkProtocol)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "vlanTag")
		delete(additionalProperties, "vlanTagMin")
		delete(additionalProperties, "vlanTagMax")
		delete(additionalProperties, "vlanSTag")
		delete(additionalProperties, "vlanCTag")
		delete(additionalProperties, "vlanCTagMin")
		delete(additionalProperties, "vlanCTagMax")
		delete(additionalProperties, "unit")
		delete(additionalProperties, "vni")
		delete(additionalProperties, "intUnit")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSimplifiedLinkProtocol struct {
	value *SimplifiedLinkProtocol
	isSet bool
}

func (v NullableSimplifiedLinkProtocol) Get() *SimplifiedLinkProtocol {
	return v.value
}

func (v *NullableSimplifiedLinkProtocol) Set(val *SimplifiedLinkProtocol) {
	v.value = val
	v.isSet = true
}

func (v NullableSimplifiedLinkProtocol) IsSet() bool {
	return v.isSet
}

func (v *NullableSimplifiedLinkProtocol) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSimplifiedLinkProtocol(val *SimplifiedLinkProtocol) *NullableSimplifiedLinkProtocol {
	return &NullableSimplifiedLinkProtocol{value: val, isSet: true}
}

func (v NullableSimplifiedLinkProtocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSimplifiedLinkProtocol) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
