/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the IBX type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IBX{}

// IBX IBX Data Center Information.
type IBX struct {
	// The Canonical URL at which the resource resides.
	Href *string `json:"href,omitempty"`
	// Indicator of a IBX resource.
	Type *string `json:"type,omitempty"`
	// Code Assigned to an Equinix IBX data center in a specified metropolitan area.
	Code *string `json:"code,omitempty"`
	// Indicates if Precision Time Service enabled in IBX or not.
	IsTimeServiceEnabled *bool `json:"isTimeServiceEnabled,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IBX IBX

// NewIBX instantiates a new IBX object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIBX() *IBX {
	this := IBX{}
	return &this
}

// NewIBXWithDefaults instantiates a new IBX object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIBXWithDefaults() *IBX {
	this := IBX{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *IBX) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IBX) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *IBX) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *IBX) SetHref(v string) {
	o.Href = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IBX) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IBX) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IBX) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *IBX) SetType(v string) {
	o.Type = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *IBX) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IBX) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *IBX) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *IBX) SetCode(v string) {
	o.Code = &v
}

// GetIsTimeServiceEnabled returns the IsTimeServiceEnabled field value if set, zero value otherwise.
func (o *IBX) GetIsTimeServiceEnabled() bool {
	if o == nil || IsNil(o.IsTimeServiceEnabled) {
		var ret bool
		return ret
	}
	return *o.IsTimeServiceEnabled
}

// GetIsTimeServiceEnabledOk returns a tuple with the IsTimeServiceEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IBX) GetIsTimeServiceEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsTimeServiceEnabled) {
		return nil, false
	}
	return o.IsTimeServiceEnabled, true
}

// HasIsTimeServiceEnabled returns a boolean if a field has been set.
func (o *IBX) HasIsTimeServiceEnabled() bool {
	if o != nil && !IsNil(o.IsTimeServiceEnabled) {
		return true
	}

	return false
}

// SetIsTimeServiceEnabled gets a reference to the given bool and assigns it to the IsTimeServiceEnabled field.
func (o *IBX) SetIsTimeServiceEnabled(v bool) {
	o.IsTimeServiceEnabled = &v
}

func (o IBX) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IBX) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.IsTimeServiceEnabled) {
		toSerialize["isTimeServiceEnabled"] = o.IsTimeServiceEnabled
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IBX) UnmarshalJSON(data []byte) (err error) {
	varIBX := _IBX{}

	err = json.Unmarshal(data, &varIBX)

	if err != nil {
		return err
	}

	*o = IBX(varIBX)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		delete(additionalProperties, "type")
		delete(additionalProperties, "code")
		delete(additionalProperties, "isTimeServiceEnabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIBX struct {
	value *IBX
	isSet bool
}

func (v NullableIBX) Get() *IBX {
	return v.value
}

func (v *NullableIBX) Set(val *IBX) {
	v.value = val
	v.isSet = true
}

func (v NullableIBX) IsSet() bool {
	return v.isSet
}

func (v *NullableIBX) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIBX(val *IBX) *NullableIBX {
	return &NullableIBX{value: val, isSet: true}
}

func (v NullableIBX) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIBX) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
