/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"fmt"
)

// GetServiceProfilesStyleParameter the model 'GetServiceProfilesStyleParameter'
type GetServiceProfilesStyleParameter string

// List of getServiceProfiles_style_parameter
const (
	GETSERVICEPROFILESSTYLEPARAMETER_MAX GetServiceProfilesStyleParameter = "MAX"
)

// All allowed values of GetServiceProfilesStyleParameter enum
var AllowedGetServiceProfilesStyleParameterEnumValues = []GetServiceProfilesStyleParameter{
	"MAX",
}

func (v *GetServiceProfilesStyleParameter) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GetServiceProfilesStyleParameter(value)
	for _, existing := range AllowedGetServiceProfilesStyleParameterEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GetServiceProfilesStyleParameter", value)
}

// NewGetServiceProfilesStyleParameterFromValue returns a pointer to a valid GetServiceProfilesStyleParameter
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGetServiceProfilesStyleParameterFromValue(v string) (*GetServiceProfilesStyleParameter, error) {
	ev := GetServiceProfilesStyleParameter(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GetServiceProfilesStyleParameter: valid values are %v", v, AllowedGetServiceProfilesStyleParameterEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GetServiceProfilesStyleParameter) IsValid() bool {
	for _, existing := range AllowedGetServiceProfilesStyleParameterEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to getServiceProfiles_style_parameter value
func (v GetServiceProfilesStyleParameter) Ptr() *GetServiceProfilesStyleParameter {
	return &v
}

type NullableGetServiceProfilesStyleParameter struct {
	value *GetServiceProfilesStyleParameter
	isSet bool
}

func (v NullableGetServiceProfilesStyleParameter) Get() *GetServiceProfilesStyleParameter {
	return v.value
}

func (v *NullableGetServiceProfilesStyleParameter) Set(val *GetServiceProfilesStyleParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableGetServiceProfilesStyleParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableGetServiceProfilesStyleParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetServiceProfilesStyleParameter(val *GetServiceProfilesStyleParameter) *NullableGetServiceProfilesStyleParameter {
	return &NullableGetServiceProfilesStyleParameter{value: val, isSet: true}
}

func (v NullableGetServiceProfilesStyleParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetServiceProfilesStyleParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
