/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
)

// checks if the GetRpOperationStatusEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRpOperationStatusEvent{}

// GetRpOperationStatusEvent struct for GetRpOperationStatusEvent
type GetRpOperationStatusEvent struct {
	SubType  *GetRpOperationStatusEventSubType `json:"subType,omitempty"`
	Severity *int32                            `json:"severity,omitempty"`
	// event description
	Message              *string        `json:"message,omitempty"`
	RoutingProtocol      *EventMetadata `json:"routingProtocol,omitempty"`
	Connection           *EventMetadata `json:"connection,omitempty"`
	Router               *EventMetadata `json:"router,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetRpOperationStatusEvent GetRpOperationStatusEvent

// NewGetRpOperationStatusEvent instantiates a new GetRpOperationStatusEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRpOperationStatusEvent() *GetRpOperationStatusEvent {
	this := GetRpOperationStatusEvent{}
	return &this
}

// NewGetRpOperationStatusEventWithDefaults instantiates a new GetRpOperationStatusEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRpOperationStatusEventWithDefaults() *GetRpOperationStatusEvent {
	this := GetRpOperationStatusEvent{}
	return &this
}

// GetSubType returns the SubType field value if set, zero value otherwise.
func (o *GetRpOperationStatusEvent) GetSubType() GetRpOperationStatusEventSubType {
	if o == nil || IsNil(o.SubType) {
		var ret GetRpOperationStatusEventSubType
		return ret
	}
	return *o.SubType
}

// GetSubTypeOk returns a tuple with the SubType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRpOperationStatusEvent) GetSubTypeOk() (*GetRpOperationStatusEventSubType, bool) {
	if o == nil || IsNil(o.SubType) {
		return nil, false
	}
	return o.SubType, true
}

// HasSubType returns a boolean if a field has been set.
func (o *GetRpOperationStatusEvent) HasSubType() bool {
	if o != nil && !IsNil(o.SubType) {
		return true
	}

	return false
}

// SetSubType gets a reference to the given GetRpOperationStatusEventSubType and assigns it to the SubType field.
func (o *GetRpOperationStatusEvent) SetSubType(v GetRpOperationStatusEventSubType) {
	o.SubType = &v
}

// GetSeverity returns the Severity field value if set, zero value otherwise.
func (o *GetRpOperationStatusEvent) GetSeverity() int32 {
	if o == nil || IsNil(o.Severity) {
		var ret int32
		return ret
	}
	return *o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRpOperationStatusEvent) GetSeverityOk() (*int32, bool) {
	if o == nil || IsNil(o.Severity) {
		return nil, false
	}
	return o.Severity, true
}

// HasSeverity returns a boolean if a field has been set.
func (o *GetRpOperationStatusEvent) HasSeverity() bool {
	if o != nil && !IsNil(o.Severity) {
		return true
	}

	return false
}

// SetSeverity gets a reference to the given int32 and assigns it to the Severity field.
func (o *GetRpOperationStatusEvent) SetSeverity(v int32) {
	o.Severity = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetRpOperationStatusEvent) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRpOperationStatusEvent) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetRpOperationStatusEvent) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetRpOperationStatusEvent) SetMessage(v string) {
	o.Message = &v
}

// GetRoutingProtocol returns the RoutingProtocol field value if set, zero value otherwise.
func (o *GetRpOperationStatusEvent) GetRoutingProtocol() EventMetadata {
	if o == nil || IsNil(o.RoutingProtocol) {
		var ret EventMetadata
		return ret
	}
	return *o.RoutingProtocol
}

// GetRoutingProtocolOk returns a tuple with the RoutingProtocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRpOperationStatusEvent) GetRoutingProtocolOk() (*EventMetadata, bool) {
	if o == nil || IsNil(o.RoutingProtocol) {
		return nil, false
	}
	return o.RoutingProtocol, true
}

// HasRoutingProtocol returns a boolean if a field has been set.
func (o *GetRpOperationStatusEvent) HasRoutingProtocol() bool {
	if o != nil && !IsNil(o.RoutingProtocol) {
		return true
	}

	return false
}

// SetRoutingProtocol gets a reference to the given EventMetadata and assigns it to the RoutingProtocol field.
func (o *GetRpOperationStatusEvent) SetRoutingProtocol(v EventMetadata) {
	o.RoutingProtocol = &v
}

// GetConnection returns the Connection field value if set, zero value otherwise.
func (o *GetRpOperationStatusEvent) GetConnection() EventMetadata {
	if o == nil || IsNil(o.Connection) {
		var ret EventMetadata
		return ret
	}
	return *o.Connection
}

// GetConnectionOk returns a tuple with the Connection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRpOperationStatusEvent) GetConnectionOk() (*EventMetadata, bool) {
	if o == nil || IsNil(o.Connection) {
		return nil, false
	}
	return o.Connection, true
}

// HasConnection returns a boolean if a field has been set.
func (o *GetRpOperationStatusEvent) HasConnection() bool {
	if o != nil && !IsNil(o.Connection) {
		return true
	}

	return false
}

// SetConnection gets a reference to the given EventMetadata and assigns it to the Connection field.
func (o *GetRpOperationStatusEvent) SetConnection(v EventMetadata) {
	o.Connection = &v
}

// GetRouter returns the Router field value if set, zero value otherwise.
func (o *GetRpOperationStatusEvent) GetRouter() EventMetadata {
	if o == nil || IsNil(o.Router) {
		var ret EventMetadata
		return ret
	}
	return *o.Router
}

// GetRouterOk returns a tuple with the Router field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRpOperationStatusEvent) GetRouterOk() (*EventMetadata, bool) {
	if o == nil || IsNil(o.Router) {
		return nil, false
	}
	return o.Router, true
}

// HasRouter returns a boolean if a field has been set.
func (o *GetRpOperationStatusEvent) HasRouter() bool {
	if o != nil && !IsNil(o.Router) {
		return true
	}

	return false
}

// SetRouter gets a reference to the given EventMetadata and assigns it to the Router field.
func (o *GetRpOperationStatusEvent) SetRouter(v EventMetadata) {
	o.Router = &v
}

func (o GetRpOperationStatusEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRpOperationStatusEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SubType) {
		toSerialize["subType"] = o.SubType
	}
	if !IsNil(o.Severity) {
		toSerialize["severity"] = o.Severity
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.RoutingProtocol) {
		toSerialize["routingProtocol"] = o.RoutingProtocol
	}
	if !IsNil(o.Connection) {
		toSerialize["connection"] = o.Connection
	}
	if !IsNil(o.Router) {
		toSerialize["router"] = o.Router
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetRpOperationStatusEvent) UnmarshalJSON(data []byte) (err error) {
	varGetRpOperationStatusEvent := _GetRpOperationStatusEvent{}

	err = json.Unmarshal(data, &varGetRpOperationStatusEvent)

	if err != nil {
		return err
	}

	*o = GetRpOperationStatusEvent(varGetRpOperationStatusEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "subType")
		delete(additionalProperties, "severity")
		delete(additionalProperties, "message")
		delete(additionalProperties, "routingProtocol")
		delete(additionalProperties, "connection")
		delete(additionalProperties, "router")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetRpOperationStatusEvent struct {
	value *GetRpOperationStatusEvent
	isSet bool
}

func (v NullableGetRpOperationStatusEvent) Get() *GetRpOperationStatusEvent {
	return v.value
}

func (v *NullableGetRpOperationStatusEvent) Set(val *GetRpOperationStatusEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRpOperationStatusEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRpOperationStatusEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRpOperationStatusEvent(val *GetRpOperationStatusEvent) *NullableGetRpOperationStatusEvent {
	return &NullableGetRpOperationStatusEvent{value: val, isSet: true}
}

func (v NullableGetRpOperationStatusEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRpOperationStatusEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
