/*
Equinix Fabric API v4

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fabricv4

import (
	"encoding/json"
	"time"
)

// checks if the TransactionStage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionStage{}

// TransactionStage struct for TransactionStage
type TransactionStage struct {
	// for internal users
	External *string `json:"external,omitempty"`
	// stage type
	Type *string `json:"type,omitempty"`
	// state
	State *string `json:"state,omitempty"`
	// Created by Date and Time
	InitiatedDateTime *time.Time `json:"initiatedDateTime,omitempty"`
	// Created by Date and Time
	CompletedDateTime *time.Time `json:"completedDateTime,omitempty"`
	// Connection name
	Duration *string `json:"duration,omitempty"`
	// for internal users
	DurationSlo          *string `json:"durationSlo,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TransactionStage TransactionStage

// NewTransactionStage instantiates a new TransactionStage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionStage() *TransactionStage {
	this := TransactionStage{}
	return &this
}

// NewTransactionStageWithDefaults instantiates a new TransactionStage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionStageWithDefaults() *TransactionStage {
	this := TransactionStage{}
	return &this
}

// GetExternal returns the External field value if set, zero value otherwise.
func (o *TransactionStage) GetExternal() string {
	if o == nil || IsNil(o.External) {
		var ret string
		return ret
	}
	return *o.External
}

// GetExternalOk returns a tuple with the External field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionStage) GetExternalOk() (*string, bool) {
	if o == nil || IsNil(o.External) {
		return nil, false
	}
	return o.External, true
}

// HasExternal returns a boolean if a field has been set.
func (o *TransactionStage) HasExternal() bool {
	if o != nil && !IsNil(o.External) {
		return true
	}

	return false
}

// SetExternal gets a reference to the given string and assigns it to the External field.
func (o *TransactionStage) SetExternal(v string) {
	o.External = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TransactionStage) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionStage) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TransactionStage) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TransactionStage) SetType(v string) {
	o.Type = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *TransactionStage) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionStage) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *TransactionStage) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *TransactionStage) SetState(v string) {
	o.State = &v
}

// GetInitiatedDateTime returns the InitiatedDateTime field value if set, zero value otherwise.
func (o *TransactionStage) GetInitiatedDateTime() time.Time {
	if o == nil || IsNil(o.InitiatedDateTime) {
		var ret time.Time
		return ret
	}
	return *o.InitiatedDateTime
}

// GetInitiatedDateTimeOk returns a tuple with the InitiatedDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionStage) GetInitiatedDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.InitiatedDateTime) {
		return nil, false
	}
	return o.InitiatedDateTime, true
}

// HasInitiatedDateTime returns a boolean if a field has been set.
func (o *TransactionStage) HasInitiatedDateTime() bool {
	if o != nil && !IsNil(o.InitiatedDateTime) {
		return true
	}

	return false
}

// SetInitiatedDateTime gets a reference to the given time.Time and assigns it to the InitiatedDateTime field.
func (o *TransactionStage) SetInitiatedDateTime(v time.Time) {
	o.InitiatedDateTime = &v
}

// GetCompletedDateTime returns the CompletedDateTime field value if set, zero value otherwise.
func (o *TransactionStage) GetCompletedDateTime() time.Time {
	if o == nil || IsNil(o.CompletedDateTime) {
		var ret time.Time
		return ret
	}
	return *o.CompletedDateTime
}

// GetCompletedDateTimeOk returns a tuple with the CompletedDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionStage) GetCompletedDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CompletedDateTime) {
		return nil, false
	}
	return o.CompletedDateTime, true
}

// HasCompletedDateTime returns a boolean if a field has been set.
func (o *TransactionStage) HasCompletedDateTime() bool {
	if o != nil && !IsNil(o.CompletedDateTime) {
		return true
	}

	return false
}

// SetCompletedDateTime gets a reference to the given time.Time and assigns it to the CompletedDateTime field.
func (o *TransactionStage) SetCompletedDateTime(v time.Time) {
	o.CompletedDateTime = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *TransactionStage) GetDuration() string {
	if o == nil || IsNil(o.Duration) {
		var ret string
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionStage) GetDurationOk() (*string, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *TransactionStage) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given string and assigns it to the Duration field.
func (o *TransactionStage) SetDuration(v string) {
	o.Duration = &v
}

// GetDurationSlo returns the DurationSlo field value if set, zero value otherwise.
func (o *TransactionStage) GetDurationSlo() string {
	if o == nil || IsNil(o.DurationSlo) {
		var ret string
		return ret
	}
	return *o.DurationSlo
}

// GetDurationSloOk returns a tuple with the DurationSlo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionStage) GetDurationSloOk() (*string, bool) {
	if o == nil || IsNil(o.DurationSlo) {
		return nil, false
	}
	return o.DurationSlo, true
}

// HasDurationSlo returns a boolean if a field has been set.
func (o *TransactionStage) HasDurationSlo() bool {
	if o != nil && !IsNil(o.DurationSlo) {
		return true
	}

	return false
}

// SetDurationSlo gets a reference to the given string and assigns it to the DurationSlo field.
func (o *TransactionStage) SetDurationSlo(v string) {
	o.DurationSlo = &v
}

func (o TransactionStage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionStage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.External) {
		toSerialize["external"] = o.External
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.InitiatedDateTime) {
		toSerialize["initiatedDateTime"] = o.InitiatedDateTime
	}
	if !IsNil(o.CompletedDateTime) {
		toSerialize["completedDateTime"] = o.CompletedDateTime
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.DurationSlo) {
		toSerialize["durationSlo"] = o.DurationSlo
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TransactionStage) UnmarshalJSON(data []byte) (err error) {
	varTransactionStage := _TransactionStage{}

	err = json.Unmarshal(data, &varTransactionStage)

	if err != nil {
		return err
	}

	*o = TransactionStage(varTransactionStage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "external")
		delete(additionalProperties, "type")
		delete(additionalProperties, "state")
		delete(additionalProperties, "initiatedDateTime")
		delete(additionalProperties, "completedDateTime")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "durationSlo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTransactionStage struct {
	value *TransactionStage
	isSet bool
}

func (v NullableTransactionStage) Get() *TransactionStage {
	return v.value
}

func (v *NullableTransactionStage) Set(val *TransactionStage) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionStage) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionStage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionStage(val *TransactionStage) *NullableTransactionStage {
	return &NullableTransactionStage{value: val, isSet: true}
}

func (v NullableTransactionStage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionStage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
